# English to Chinese Name Dictionary (Expanded)
CHEMICAL_NAMES_ZH_EXPANDED = {
    "(+)-trans-chrysanthemic acid": "(+)-反式菊酸",
    "(-)-adenosine": "腺苷",
    "(-)-alpha-phellandrene": "(-)-α-水芹烯",
    "(-)-alpha-pinene": "(-)-α-蒎烯",
    "(-)-beta-pinene": "(-)-β-蒎烯",
    "(-)-bornyl acetate": "(-)-乙酸龍腦酯",
    "(-)-isocaryophyllene": "(-)-異石竹烯",
    "(1,2-dibromoethyl)benzene": "(1,2-二溴乙基)苯",
    "(1,5-cyclooctadiene)(methoxy)iridium(i) dimer": "(1,5-環辛二烯)(甲氧基)銥(I)二聚體",
    "(1-chloroethyl)benzene": "(1-氯乙基)苯",
    "(2e,4z)-undeca-2,4-dien-1-ol": "(2E,4Z)-十一-2,4-二烯-1-醇",
    "(3-aminopropyl)trimethoxysilane (aptms)": "(3-胺基丙基)三甲氧基矽烷",
    "(3-chloropropyl)trichlorosilane": "(3-氯丙基)三氯矽烷",
    "(3-glycidyloxypropyl)trimethoxysilane": "(3-縮水甘油氧基丙基)三甲氧基矽烷",
    "(3-isocyanatopropyl)triethoxysilane": "(3-異氰酸基丙基)三乙氧基矽烷",
    "(3-mercaptopropyl)trimethoxysilane": "(3-巰基丙基)三甲氧基矽烷",
    "(3-mercaptopropyl)trimethoxysilane (mptms)": "(3-巰基丙基)三甲氧基矽烷",
    "(4-nitrobenzyl)mercaptan": "4-硝基苄硫醇",
    "(5-formylfuran-2-yl)boronic acid": "5-甲醛基-2-呋喃硼酸",
    "(bromomethyl)pentafluorobenzene": "(溴甲基)五氟苯",
    "(r)-(+)-4-benzyl-2-oxazolidinone": "(R)-(+)-4-芐基-2-噁唑烷酮",
    "(s)-(+)-2-methylbutyric acid": "(S)-(+)-2-甲基丁酸",
    "(s)-(-)-2-methylbutanol": "(S)-(-)-2-甲基丁醇",
    "(s)-(-)-alpha-methylbenzylamine": "(S)-(-)-α-甲基苄胺",
    "(z)-11-hexadecenyl acetate": "(Z)-11-十六烯乙酸酯",
    "(z)-11-tetradecen-1-yl acetate": "(Z)-11-十四烯-1-醇乙酸酯",
    "(z)-9-dodecenyl acetate": "(Z)-9-十二烯乙酸酯",
    "(±)-2,2'-bis(diphenylphosphino)-1,1'-binaphthalene (binap)": "(±)-2,2'-雙(二苯基膦)-1,1'-聯萘 (BINAP)",
    "(±)-2,2'-bis(diphenylphosphino)-1,1'-binaphthyl (binap)": "2,2'-雙",
    "1,1'-bis(diphenylphosphino)ferrocene (dppf)": "1,1'-雙",
    "1,1'-bis(diphenylphosphino)ferrocene-palladium(ii) dichloride": "[1,1'-雙",
    "1,1'-thiocarbonyldiimidazole": "1,1'-硫羰基二咪唑",
    "1,1,1,3,3,3-hexafluoro-2-propanol": "1,1,1,3,3,3-六氟-2-丙醇",
    "1,1,1,3,3,3-hexamethyldisilazane (hmds)": "六甲基二矽氮烷",
    "1,1,1-trichloroethane": "1,1,1-三氯乙烷",
    "1,1,2,2-tetrachloroethane-d2": "1,1,2,2-四氯乙烷-d2",
    "1,1,2,2-tetrakis(4-bromophenyl)ethene": "1,1,2,2-四",
    "1,1,2-trichloro-1,2,2-trifluoroethane": "1,1,2-三氯-1,2,2-三氟乙烷",
    "1,1,3,3-tetramethoxypropane": "1,1,3,3-四甲氧基丙烷",
    "1,1-cyclobutanedicarboxylic acid": "1,1-環丁烷二甲酸",
    "1,1-diphenylethylene": "1,1-二苯基乙烯",
    "1,10-decanediol": "1,10-癸二醇",
    "1,10-phenanthroline": "1,10-菲羅啉",
    "1,10-phenanthroline monohydrate": "1,10-菲羅啉一水合物",
    "1,12-diaminododecane": "1,12-十二烷二胺",
    "1,12-dibromododecane": "1,12-二溴十二烷",
    "1,12-dodecanediol": "1,12-十二烷二醇",
    "1,16-hexadecanediol": "1,16-十六烷二醇",
    "1,18-octadecanedioic acid": "十八烷二酸",
    "1,2,3-benzotriazole": "1,2,3-苯并三唑",
    "1,2,4,5-tetrakis(bromomethyl)benzene": "1,2,4,5-四",
    "1,2,4-trichlorobenzene": "1,2,4-三氯苯",
    "1,2,4-trimethylbenzene": "1,2,4-三甲苯",
    "1,2-di(3-thienyl)-1,2-ethanedione": "1,2-二",
    "1,2-diaminoanthraquinone": "1,2-二胺基蒽醌",
    "1,2-dibromo-4,5-difluorobenzene": "1,2-二溴-4,5-二氟苯",
    "1,2-dibromobenzene": "1,2-二溴苯",
    "1,2-dibromoethane": "1,2-二溴乙烷",
    "1,2-dibromoethene (mixed isomers)": "1,2-二溴乙烯",
    "1,2-dichloroethane": "1,2-二氯乙烷",
    "1,2-dicyanocyclobutane": "1,2-二氰基環丁烷",
    "1,2-dimethoxybenzene": "1,2-二甲氧基苯",
    "1,2-dimethoxybenzene (veratrole)": "1,2-二甲氧基苯",
    "1,2-dimethoxyethane": "1,2-二甲氧基乙烷",
    "1,2-epoxypropane (propylene oxide)": "環氧丙烷",
    "1,2-ethanedithiol": "1,2-乙二硫醇",
    "1,2-naphthoquinone": "1,2-萘醌",
    "1,2-phenylenediacetonitrile": "1,2-苯二乙腈",
    "1,3,5-benzenetricarboxaldehyde": "1,3,5-苯三甲醛",
    "1,3,5-tribromo-2,4,6-trimethylbenzene": "1,3,5-三溴-2,4,6-三甲基苯",
    "1,3,5-tribromobenzene": "1,3,5-三溴苯",
    "1,3,5-trimethylbenzene (mesitylene)": "1,3,5-三甲苯",
    "1,3,5-tris(bromomethyl)benzene": "1,3,5-三",
    "1,3-benzodioxole": "1,3-苯并戴奧辛",
    "1,3-bis(1-isocyanato-1-methylethyl)benzene (tmxdi)": "1,3-雙",
    "1,3-bis(diphenylphosphino)propane (dppp)": "1,3-雙",
    "1,3-diaminopropane": "1,3-丙二胺",
    "1,3-dibromo-5,5-dimethylhydantoin": "1,3-二溴-5,5-二甲基海因",
    "1,3-dibromobenzene": "1,3-二溴苯",
    "1,3-dibromopropane": "1,3-二溴丙烷",
    "1,3-dichloro-2-iodobenzene": "1,3-二氯-2-碘苯",
    "1,3-dimethyl-3,4,5,6-tetrahydro-2(1h)-pyrimidinone": "1,3-二甲基-3,4,5,6-四氫-2",
    "1,3-dithiolane-2-thione": "1,3-二硫雜環戊烷-2-硫酮",
    "1,3-propanediol": "1,3-丙二醇",
    "1,4,5,8-naphthalenetetracarboxylic dianhydride": "1,4,5,8-萘四甲酸二酐",
    "1,4-anthraquinone": "1,4-蒽醌",
    "1,4-bis(trimethylsilyl)-1,3-butadiyne": "1,4-雙",
    "1,4-butanediol": "1,4-丁二醇",
    "1,4-butynediol": "1,4-丁炔二醇",
    "1,4-cyclohexadiene": "1,4-環己二烯",
    "1,4-cyclohexanedione": "1,4-環己二酮",
    "1,4-di(2-thienyl)-1,4-butanedione": "1,4-二",
    "1,4-diaminoanthraquinone": "1,4-二胺基蒽醌",
    "1,4-diaminobutane": "1,4-二胺基丁烷",
    "1,4-dibromo-2,5-difluorobenzene": "1,4-二溴-2,5-二氟苯",
    "1,4-dibromo-2,5-dimethoxybenzene": "1,4-二溴-2,5-二甲氧基苯",
    "1,4-dibromo-2-nitrobenzene": "1,4-二溴-2-硝基苯",
    "1,4-dibromobenzene": "1,4-二溴苯",
    "1,4-dibromobutane": "1,4-二溴丁烷",
    "1,4-dibromotetrafluorobenzene": "1,4-二溴四氟苯",
    "1,4-dichloro-2-butyne": "1,4-二氯-2-丁炔",
    "1,4-dichlorobenzene": "1,4-二氯苯",
    "1,4-dihydroxynaphthalene": "1,4-二羥基萘",
    "1,4-diiodobenzene": "1,4-二碘苯",
    "1,4-dimethoxybenzene": "1,4-二甲氧基苯",
    "1,4-dioxane": "1,4-二氧六環",
    "1,4-naphthoquinone": "1,4-萘醌",
    "1,4-phenylenediacetonitrile": "1,4-苯二乙腈",
    "1,4-phenylenediboronic acid, bis(pinacol) ester": "1,4-苯二硼酸雙",
    "1,5-diaminoanthraquinone": "1,5-二胺基蒽醌",
    "1,5-diaminonaphthalene": "1,5-二胺基萘",
    "1,5-dibromopentane": "1,5-二溴戊烷",
    "1,5-dichloroanthraquinone": "1,5-二氯蒽醌",
    "1,5-hexadiene": "1,5-己二烯",
    "1,6-dibromohexane": "1,6-二溴己烷",
    "1,6-hexanediamine": "1,6-己二胺",
    "1,6-hexanediol": "1,6-己二醇",
    "1,6-hexanedithiol": "1,6-己二硫醇",
    "1,7-dibromoheptane": "1,7-二溴庚烷",
    "1,7-heptanediol": "1,7-庚二醇",
    "1,8-diaminonaphthalene": "1,8-二胺基萘",
    "1,8-diazabicyclo[5.4.0]undec-7-ene": "1,8-二氮雜雙環[5.4.0]十一-7-烯",
    "1,8-dibromoanthracene": "1,8-二溴蒽",
    "1,8-dibromooctane": "1,8-二溴辛烷",
    "1,8-dichloroanthraquinone": "1,8-二氯蒽醌",
    "1,8-diiodonaphthalene": "1,8-二碘萘",
    "1,8-naphthalic anhydride": "1,8-萘二甲酸酐",
    "1,8-octanediol": "1,8-辛二醇",
    "1,8-octanedithiol": "1,8-辛二硫醇",
    "1,9-dibromononane": "1,9-二溴壬烷",
    "1,9-nonanediol": "1,9-壬二醇",
    "1-(3-dimethylaminopropyl)-3-ethylcarbodiimide": "1-",
    "1-(3-dimethylaminopropyl)-3-ethylcarbodiimide hydrochloride": "1-",
    "1-(4-bromophenyl)-1,2,2-triphenylethylene": "1-",
    "1-(trimethylsilyl)propyne": "1-",
    "1-aminoanthraquinone": "1-胺基蒽醌",
    "1-bromo-2,3-difluoro-4-methoxybenzene": "1-溴-2,3-二氟-4-甲氧基苯",
    "1-bromo-2-(2-methoxyethoxy)ethane": "1-溴-2-",
    "1-bromo-2-fluorobenzene": "1-溴-2-氟苯",
    "1-bromo-2-iodobenzene": "1-溴-2-碘苯",
    "1-bromo-2-methylnaphthalene": "1-溴-2-甲基萘",
    "1-bromo-2-methylpropane": "1-溴-2-甲基丙烷",
    "1-bromo-2-nitrobenzene": "1-溴-2-硝基苯",
    "1-bromo-3,4,5-trifluorobenzene": "1-溴-3,4,5-三氟苯",
    "1-bromo-3,5-difluorobenzene": "1-溴-3,5-二氟苯",
    "1-bromo-3,5-dimethoxybenzene": "1-溴-3,5-二甲氧基苯",
    "1-bromo-3-chloropropane": "1-溴-3-氯丙烷",
    "1-bromo-3-methylbutane": "1-溴-3-甲基丁烷",
    "1-bromo-3-nitrobenzene": "1-溴-3-硝基苯",
    "1-bromo-4-(n-butyl)benzene": "1-溴-4-正丁基苯",
    "1-bromo-4-chlorobenzene": "1-溴-4-氯苯",
    "1-bromo-4-hexylbenzene": "1-溴-4-己基苯",
    "1-bromo-4-iodobenzene": "1-溴-4-碘苯",
    "1-bromo-4-n-propylbenzene": "1-溴-4-正丙基苯",
    "1-bromo-4-nitrobenzene": "1-溴-4-硝基苯",
    "1-bromo-4-phenylbutane": "1-溴-4-苯基丁烷",
    "1-bromobutane": "1-溴丁烷",
    "1-bromodecane": "1-溴癸烷",
    "1-bromodocosane": "1-溴二十二烷",
    "1-bromododecane": "1-溴十二烷",
    "1-bromoeicosane": "1-溴二十烷",
    "1-bromoheptadecane": "1-溴十七烷",
    "1-bromohexadecane": "1-溴十六烷",
    "1-bromohexane": "1-溴己烷",
    "1-bromonaphthalene": "1-溴萘",
    "1-bromononane": "1-溴壬烷",
    "1-bromooctadecane": "1-溴十八烷",
    "1-bromooctane": "1-溴辛烷",
    "1-bromopentadecane": "1-溴十五烷",
    "1-bromopentane": "1-溴戊烷",
    "1-bromopropane": "1-溴丙烷",
    "1-bromopyrene": "1-溴芘",
    "1-bromotetradecane": "1-溴十四烷",
    "1-bromoundecane": "1-溴十一烷",
    "1-butyl alcohol": "1-丁醇",
    "1-butyl alcohol (n-butanol)": "正丁醇",
    "1-butyl-3-methylimidazolium hexafluorophosphate": "1-丁基-3-甲基咪唑六氟磷酸鹽",
    "1-butyl-4-ethynylbenzene": "1-丁基-4-乙炔基苯",
    "1-butylboronic acid": "1-丁基硼酸",
    "1-chloro-2,5-dibromobenzene": "1-氯-2,5-二溴苯",
    "1-decanethiol": "1-癸硫醇",
    "1-decene": "1-癸烯",
    "1-decyne": "1-癸炔",
    "1-dodecanethiol": "1-十二硫醇",
    "1-dodecanol": "1-十二醇",
    "1-dodecyne": "1-十二炔",
    "1-eicosanol": "1-二十醇",
    "1-eicosene": "1-二十烯",
    "1-ethyl-3-(3-dimethylaminopropyl)carbodiimide (edc)": "1-乙基-3-",
    "1-ethyl-3-methylimidazolium chloride": "1-乙基-3-甲基咪唑氯鹽",
    "1-ethylpropylamine": "1-乙基丙胺",
    "1-fluoro-4-nitrobenzene": "1-氟-4-硝基苯",
    "1-formylpiperidine": "1-甲醯基哌啶",
    "1-heptadecanol": "1-十七醇",
    "1-heptadecyne": "1-十七炔",
    "1-heptanethiol": "1-庚硫醇",
    "1-heptene": "1-庚烯",
    "1-hexadecanethiol": "1-十六硫醇",
    "1-hexadecene": "1-十六烯",
    "1-hexadecyne": "1-十六炔",
    "1-hexanethiol": "1-己硫醇",
    "1-hexyl-3-methylimidazolium hexafluorophosphate": "1-己基-3-甲基咪唑六氟磷酸鹽",
    "1-hexyne": "1-己炔",
    "1-hydroxy-2-naphthoic acid": "1-羥基-2-萘甲酸",
    "1-iodo-1h,1h,2h,2h-perfluorodecane": "1H,1H,2H,2H-全氟碘代癸烷",
    "1-iodo-3,5-dimethylbenzene": "1-碘-3,5-二甲苯",
    "1-iodo-4-nitrobenzene": "1-碘-4-硝基苯",
    "1-iododecane": "1-碘癸烷",
    "1-iodonaphthalene": "1-碘萘",
    "1-iodopentane": "1-碘戊烷",
    "1-methyl-3-propylimidazolium iodide": "1-甲基-3-丙基咪唑碘鹽",
    "1-methylindole": "1-甲基吲哚",
    "1-naphthaldehyde": "1-萘甲醛",
    "1-naphthoic acid": "1-萘甲酸",
    "1-naphthol": "1-萘酚",
    "1-naphthylacetic acid": "1-萘乙酸",
    "1-nitroso-2-naphthol": "1-亞硝基-2-萘酚",
    "1-nonadecanol": "1-十九醇",
    "1-nonadecene": "1-十九烯",
    "1-nonanol": "1-壬醇",
    "1-nonyne": "1-壬炔",
    "1-octacosanol": "1-二十八醇",
    "1-octadecanamine": "十八胺",
    "1-octadecanethiol": "1-十八烷硫醇",
    "1-octadecanol (stearyl alcohol)": "1-十八醇",
    "1-octadecene": "1-十八烯",
    "1-octanethiol": "1-辛硫醇",
    "1-octanol": "1-辛醇",
    "1-octene": "1-辛烯",
    "1-octyne": "1-辛炔",
    "1-pentadecene": "1-十五烯",
    "1-pentadecyne": "1-十五炔",
    "1-pentanethiol": "1-戊硫醇",
    "1-pentanol": "1-戊醇",
    "1-penten-3-ol": "1-戊烯-3-醇",
    "1-pentyne": "1-戊炔",
    "1-propanephosphonic dichloride": "1-丙基膦酸二氯",
    "1-propanethiol": "1-丙硫醇",
    "1-pyrenecarboxaldehyde": "1-芘甲醛",
    "1-pyrenemethylamine hydrochloride": "1-芘甲胺鹽酸鹽",
    "1-tetracosanol": "1-二十四醇",
    "1-tetradecene": "1-十四烯",
    "1-tetradecyne": "1-十四炔",
    "1-tetralone": "1-四氫萘酮",
    "1-tridecene": "1-十三烯",
    "1-tridecyne": "1-十三炔",
    "1-undecyne": "1-十一炔",
    "10,12-octadecadiynoic acid": "10,12-十八碳二炔酸",
    "10,12-pentacosadiynoic acid": "10,12-二十五碳二炔酸",
    "10-benzhydrylidene-9-anthrone": "10-二苯亞甲基-9-蒽酮",
    "10-bromo-1-decanol": "10-溴-1-癸醇",
    "10-bromo-1-decene": "10-溴-1-癸烯",
    "10-undecyn-1-ol": "10-十一炔-1-醇",
    "10-undecynoic acid": "10-十一炔酸",
    "10h-phenoselenazine": "10H-吩硒嗪",
    "11-aminoundecanoic acid": "11-胺基十一酸",
    "11-bromo-1-undecanol": "11-溴-1-十一醇",
    "11-bromo-1-undecene": "11-溴-1-十一烯",
    "11-bromoundecanoic acid": "11-溴十一酸",
    "11-dodecen-1-yl acetate": "11-十二烯醇乙酸酯",
    "11-mercapto-1-undecanol": "11-巰基-1-十一醇",
    "11-mercaptoundecanoic acid": "11-巰基十一酸",
    "12-hydroxydodecanoic acid": "12-羥基十二酸",
    "12-tricosanone": "12-二十三酮",
    "15-hydroxypentadecanoic acid": "15-羥基十五酸",
    "16-hydroxyhexadecanoic acid": "16-羥基十六酸",
    "16-mercaptohexadecanoic acid": "16-巰基十六酸",
    "18-crown-6": "18-冠-6",
    "1h,1h,2h,2h-perfluorodecanethiol": "1H,1H,2H,2H-全氟癸硫醇",
    "1h,1h,2h,2h-perfluorodecyl iodide": "1H,1H,2H,2H-全氟碘代癸烷",
    "1h,1h,2h,2h-perfluorodecyltrichlorosilane": "(1H,1H,2H,2H-全氟癸基)三氯矽烷",
    "1h-benzo[d][1,2,3]triazol-1-ol (hobt)": "1-羥基苯并三唑",
    "2'-aminoacetophenone": "2'-胺基苯乙酮",
    "2'-bromoacetophenone": "2'-溴苯乙酮",
    "2'-hydroxy-1'-acetonaphthone": "2'-羥基-1'-乙醯萘酮",
    "2,1,3-benzothiadiazole": "2,1,3-苯并噻二唑",
    "2,2',4,4',6,6'-hexamethylbiphenyl": "2,2',4,4',6,6'-六甲基聯苯",
    "2,2'-bipyridyl": "2,2'-聯吡啶",
    "2,2'-bis(diphenylphosphino)-1,1'-binaphthyl (binap)": "2,2'-雙",
    "2,2'-bithiophene": "2,2'-聯噻吩",
    "2,2'-dipyridyl disulfide": "2,2'-二吡啶二硫醚",
    "2,2':5',2''-terthiophene": "2,2':5',2''-三噻吩",
    "2,2,2-trifluoroacetamide": "2,2,2-三氟乙醯胺",
    "2,2,2-trifluoroethanol": "2,2,2-三氟乙醇",
    "2,2,4-trimethylpentane": "2,2,4-三甲基戊烷",
    "2,2,4-trimethylpentane (isooctane)": "2,2,4-三甲基戊烷",
    "2,2,6,6-tetramethyl-4-piperidylamine": "2,2,6,6-四甲基-4-哌啶胺",
    "2,2-diphenyl-1-picrylhydrazyl (dpph)": "2,2-二苯基-1-苦味基肼",
    "2,3,5,6-tetrafluorobenzyl bromide": "2,3,5,6-四氟苄基溴",
    "2,3,5,6-tetramethylpyrazine": "2,3,5,6-四甲基吡嗪",
    "2,3,5-trimethylphenol": "2,3,5-三甲基苯酚",
    "2,3-butanedione": "2,3-丁二酮",
    "2,3-diaminonaphthalene": "2,3-二胺基萘",
    "2,3-diaminophenazine": "2,3-二胺基吩嗪",
    "2,3-diaminopropionic acid monohydrochloride": "2,3-二胺基丙酸鹽酸鹽",
    "2,3-dibromomaleimide": "2,3-二溴馬來醯亞胺",
    "2,3-dibromothiophene": "2,3-二溴噻吩",
    "2,3-dichloro-5,6-dicyano-1,4-benzoquinone (ddq)": "2,3-二氯-5,6-二氰基對苯醌",
    "2,3-dicyanohydroquinone": "2,3-二氰基對苯二酚",
    "2,3-dihydroxynaphthalene": "2,3-二羥基萘",
    "2,3-dimethyl-1,3-butadiene": "2,3-二甲基-1,3-丁二烯",
    "2,3-naphthalenedicarboxylic anhydride": "2,3-萘二甲酸酐",
    "2,3-pyrazinedicarboxylic acid": "2,3-吡嗪二羧酸",
    "2,3-xylenol": "2,3-二甲基苯酚",
    "2,3-xylidine": "2,3-二甲基苯胺",
    "2,4,6,8-tetramethyl-2,4,6,8-tetravinylcyclotetrasiloxane": "四甲基四乙烯基環四矽氧烷",
    "2,4,6-trimethylpyridine (collidine)": "2,4,6-三甲基吡啶",
    "2,4-dimethylphenol": "2,4-二甲基苯酚",
    "2,4-dodecadien-1-ol": "2,4-十二碳二烯-1-醇",
    "2,5-bis(5-tert-butyl-2-benzoxazolyl)thiophene": "2,5-雙",
    "2,5-dibromo-p-xylene": "2,5-二溴對二甲苯",
    "2,5-dibromohydroquinone": "2,5-二溴對苯二酚",
    "2,5-dibromopyridine": "2,5-二溴吡啶",
    "2,5-dibromothiophene": "2,5-二溴噻吩",
    "2,5-difluoro-1,4-phenylenediboronic acid": "2,5-二氟-1,4-苯二硼酸",
    "2,5-dihydroxy-1,4-benzoquinone": "2,5-二羥基-1,4-苯醌",
    "2,5-dimethoxybenzaldehyde": "2,5-二甲氧基苯甲醛",
    "2,5-dimethoxybenzyl alcohol": "2,5-二甲氧基苯甲醇",
    "2,5-dimethyl-1,4-phenylenediamine": "2,5-二甲基-1,4-苯二胺",
    "2,5-thiophenedicarboxaldehyde": "2,5-噻吩二甲醛",
    "2,5-xylenol": "2,5-二甲基苯酚",
    "2,6-diaminoanthraquinone": "2,6-二胺基蒽醌",
    "2,6-diaminopyridine": "2,6-二胺基吡啶",
    "2,6-diaminotoluene": "2,6-二胺基甲苯",
    "2,6-dibromopyridine": "2,6-二溴吡啶",
    "2,6-difluoroaniline": "2,6-二氟苯胺",
    "2,6-difluorobenzoic acid": "2,6-二氟苯甲酸",
    "2,6-difluorobenzonitrile": "2,6-二氟苯甲腈",
    "2,6-difluoronitrobenzene": "2,6-二氟硝基苯",
    "2,6-difluorophenol": "2,6-二氟苯酚",
    "2,6-naphthalenedicarboxylic acid": "2,6-萘二甲酸",
    "2,6-xylenol": "2,6-二甲基苯酚",
    "2,7-dibromo-9-fluorenone": "2,7-二溴-9-芴酮",
    "2,7-dibromo-9h-carbazole": "2,7-二溴咔唑",
    "2,7-dibromo-9h-fluoren-9-one": "2,7-二溴-9-芴酮",
    "2,7-dihydroxynaphthalene": "2,7-二羥基萘",
    "2,7-dinitro-9-fluorenone": "2,7-二硝基-9-芴酮",
    "2,7-naphthalenediol": "2,7-萘二酚",
    "2-(1-cyclohexenyl)cyclohexanone": "2-",
    "2-(4-tert-butylphenyl)-5-(4-biphenylyl)-1,3,4-oxadiazole": "2-",
    "2-(dicyclohexylphosphino)biphenyl": "2-",
    "2-(tributylstannyl)thiophene": "2-",
    "2-[4-(carboxymethoxy)phenoxy]acetic acid": "對苯二氧乙酸",
    "2-acetonaphthone": "2-乙醯萘",
    "2-acetyl-5-chlorothiophene": "2-乙醯基-5-氯噻吩",
    "2-acetylthiophene": "2-乙醯基噻吩",
    "2-amino-4-methylbenzothiazole": "2-胺基-4-甲基苯并噻唑",
    "2-aminoanthracene": "2-胺基蒽",
    "2-aminobenzene sulfonic acid": "2-胺基苯磺酸",
    "2-aminobiphenyl": "2-胺基聯苯",
    "2-aminodiphenylamine": "2-胺基二苯胺",
    "2-aminoheptane": "2-胺基庚烷",
    "2-aminophenol": "2-胺基苯酚",
    "2-aminopyridine": "2-胺基吡啶",
    "2-benzoylbenzoic acid": "2-苯甲醯基苯甲酸",
    "2-bromo-1,3-difluoro-5-iodobenzene": "2-溴-1,3-二氟-5-碘苯",
    "2-bromo-1-phenylethanone": "2-溴苯乙酮",
    "2-bromo-3-fluorophenol": "2-溴-3-氟苯酚",
    "2-bromo-3-hexylthiophene": "2-溴-3-己基噻吩",
    "2-bromo-3-methoxyphenol": "2-溴-3-甲氧基苯酚",
    "2-bromo-4,5-difluorophenol": "2-溴-4,5-二氟苯酚",
    "2-bromo-4,5-difluorophenylboronic acid": "2-溴-4,5-二氟苯硼酸",
    "2-bromo-5-iodothiophene": "2-溴-5-碘噻吩",
    "2-bromo-6-fluorophenol": "2-溴-6-氟苯酚",
    "2-bromo-6-methoxynaphthalene": "2-溴-6-甲氧基萘",
    "2-bromo-6-methoxyphenol": "2-溴-6-甲氧基苯酚",
    "2-bromoanthracene": "2-溴蒽",
    "2-bromobenzoic acid": "2-溴苯甲酸",
    "2-bromobiphenyl": "2-溴聯苯",
    "2-bromocarbazole": "2-溴咔唑",
    "2-bromoethanol": "2-溴乙醇",
    "2-bromofluorene": "2-溴芴",
    "2-bromofluorobenzene": "2-溴氟苯",
    "2-bromoindene": "2-溴茚",
    "2-bromomesitylene": "2-溴均三甲苯",
    "2-bromonaphthalene": "2-溴萘",
    "2-bromophenol": "2-溴苯酚",
    "2-bromophenylacetic acid": "2-溴苯乙酸",
    "2-bromophenylboronic acid": "2-溴苯硼酸",
    "2-bromothiophene": "2-溴噻吩",
    "2-bromotoluene": "2-溴甲苯",
    "2-carboxybenzaldehyde": "2-羧基苯甲醛",
    "2-chloro-1,3,2-dioxaphospholane": "2-氯-1,3,2-二氧磷雜環戊烷",
    "2-chlorobenzaldehyde": "2-氯苯甲醛",
    "2-chloronaphthalene": "2-氯萘",
    "2-chloropropane": "2-氯丙烷",
    "2-cyanopyridine": "2-氰基吡啶",
    "2-cyclohexyl-1-propanol": "2-環己基-1-丙醇",
    "2-cyclopenten-1-one": "2-環戊烯-1-酮",
    "2-dimethylaminoethanol": "2-二甲胺基乙醇",
    "2-ethylhexoic acid": "2-乙基己酸",
    "2-ethylhexyl acrylate": "丙烯酸-2-乙基己酯",
    "2-ethylhexyl bromide": "2-乙基溴己烷",
    "2-ethylhexylamine": "2-乙基己胺",
    "2-fluoro-4-methoxyaniline": "2-氟-4-甲氧基苯胺",
    "2-fluorobenzyl bromide": "2-氟溴化苄",
    "2-furoyl chloride": "2-呋喃甲醯氯",
    "2-hydroxyethyl methacrylate": "甲基丙烯酸-2-羥乙酯",
    "2-iodo-5-methylbenzoic acid": "2-碘-5-甲基苯甲酸",
    "2-iodoaniline": "2-碘苯胺",
    "2-iodoanisole": "2-碘苯甲醚",
    "2-iodobenzoic acid": "2-碘苯甲酸",
    "2-iodopropane": "2-碘丙烷",
    "2-isopropoxy-4,4,5,5-tetramethyl-1,3,2-dioxaborolane": "2-異丙氧基-4,4,5,5-四甲基-1,3,2-二氧硼雜環戊烷",
    "2-mercaptobenzimidazole": "2-巰基苯并咪唑",
    "2-mercaptopyridine": "2-巰基吡啶",
    "2-methoxyphenol": "2-甲氧基苯酚",
    "2-methoxyphenylboronic acid": "2-甲氧基苯硼酸",
    "2-methoxythiophene": "2-甲氧基噻吩",
    "2-methyl-3-buten-2-ol": "2-甲基-3-丁烯-2-醇",
    "2-methyl-3-butyn-2-ol": "2-甲基-3-丁炔-2-醇",
    "2-methylbenzophenone": "2-甲基二苯甲酮",
    "2-methylbutyric acid": "2-甲基丁酸",
    "2-methylbutyryl chloride": "2-甲基丁醯氯",
    "2-methylene-1,3,3-trimethylindoline": "2-亞甲基-1,3,3-三甲基吲哚啉",
    "2-methylindole": "2-甲基吲哚",
    "2-methylthiophene": "2-甲基噻吩",
    "2-naphthaldehyde": "2-萘甲醛",
    "2-naphthaleneboronic acid": "2-萘硼酸",
    "2-naphthol": "2-萘酚",
    "2-nitroaniline": "2-硝基苯胺",
    "2-nitrobenzaldehyde": "2-硝基苯甲醛",
    "2-nitroethanol": "2-硝基乙醇",
    "2-nitropropane": "2-硝基丙烷",
    "2-nonylbenzimidazole": "2-壬基苯并咪唑",
    "2-phenethyl acetate": "乙酸-2-苯乙酯",
    "2-phenoxyethanol": "2-苯氧基乙醇",
    "2-picolinic acid": "2-吡啶甲酸",
    "2-propanethiol": "2-丙硫醇",
    "2-pyridineacetonitrile": "2-吡啶乙腈",
    "2-pyridylacetic acid hydrochloride": "2-吡啶乙酸鹽酸鹽",
    "2-thiophenecarboxylic acid": "2-噻吩甲酸",
    "2-undecyl-1h-imidazole": "2-十一烷基咪唑",
    "3,3'-diaminobenzidine (dab)": "3,3'-二胺基聯苯胺",
    "3,3'-dibromo-5,5'-bis(trimethylsilyl)-2,2'-bithiophene": "3,3'-二溴-5,5'-雙",
    "3,3-dimethyl-2-butanone": "3,3-二甲基-2-丁酮",
    "3,3-dimethylacryloyl chloride": "3,3-二甲基丙烯醯氯",
    "3,4,5-trichlorophenylboronic acid": "3,4,5-三氯苯硼酸",
    "3,4,5-trifluorobenzyl bromide": "3,4,5-三氟苄基溴",
    "3,4,5-trifluorophenylboronic acid": "3,4,5-三氟苯硼酸",
    "3,4-bis(methoxycarbonyl)phenylboronic acid": "3,4-雙",
    "3,4-dibromothiophene": "3,4-二溴噻吩",
    "3,4-dichlorobenzoyl chloride": "3,4-二氯苯甲醯氯",
    "3,4-dichlorophenylboronic acid": "3,4-二氯苯硼酸",
    "3,4-difluorophenylboronic acid": "3,4-二氟苯硼酸",
    "3,4-dihydro-2h-pyran": "3,4-二氫-2H-吡喃",
    "3,4-dimethylbenzoic acid": "3,4-二甲基苯甲酸",
    "3,4-dimethylphenol": "3,4-二甲基苯酚",
    "3,5-bis(trifluoromethyl)benzyl bromide": "3,5-雙",
    "3,5-bis(trifluoromethyl)bromobenzene": "3,5-雙",
    "3,5-bis(trifluoromethyl)phenylmagnesium bromide": "3,5-雙",
    "3,5-diaminobenzoic acid": "3,5-二胺基苯甲酸",
    "3,5-dichlorophenylboronic acid": "3,5-二氯苯硼酸",
    "3,5-difluorobenzoic acid": "3,5-二氟苯甲酸",
    "3,5-difluorophenylboronic acid": "3,5-二氟苯硼酸",
    "3,5-dihydroxybenzoic acid": "3,5-二羥基苯甲酸",
    "3,5-dimethylphenol": "3,5-二甲基苯酚",
    "3,6-di-2-pyridyl-1,2,4,5-tetrazine": "3,6-二",
    "3,6-dibromo-9h-carbazole": "3,6-二溴咔唑",
    "3,6-dibromocarbazole": "3,6-二溴咔唑",
    "3,7-dihydrobenzo[1,2-b:4,5-b']difuran-2,6-dione": "3,7-二氫苯并[1,2-b:4,5-b']二呋喃-2,6-二酮",
    "3-(dicyanomethylidene)indan-1-one": "3-二氰亞甲基-1-茚酮",
    "3-(ethoxycarbonyl)phenylboronic acid": "3-",
    "3-(p-methoxyphenyl)propyltrichlorosilane": "3-",
    "3-(pyridin-2-yl)-2h-chromen-2-one": "3-",
    "3-amino-1-propanol (propanolamine)": "3-胺基-1-丙醇",
    "3-amino-2-naphthoic acid": "3-胺基-2-萘甲酸",
    "3-aminocrotononitrile": "3-胺基巴豆腈",
    "3-aminopropyltriethoxysilane": "3-胺基丙基三乙氧基矽烷",
    "3-aminopyridine": "3-胺基吡啶",
    "3-bromo-1-propanol": "3-溴-1-丙醇",
    "3-bromo-2-hydroxypyridine": "3-溴-2-羥基吡啶",
    "3-bromo-4-iodotoluene": "3-溴-4-碘甲苯",
    "3-bromoanisole": "3-溴苯甲醚",
    "3-bromobenzaldehyde": "3-溴苯甲醛",
    "3-bromobenzoic acid": "3-溴苯甲酸",
    "3-bromobiphenyl": "3-溴聯苯",
    "3-bromofluorobenzene": "3-溴氟苯",
    "3-bromophenol": "3-溴苯酚",
    "3-bromophenylboronic acid": "3-溴苯硼酸",
    "3-bromopropionitrile": "3-溴丙腈",
    "3-bromopropionyl chloride": "3-溴丙醯氯",
    "3-bromopropyne": "3-溴丙炔",
    "3-bromopyridine": "3-溴吡啶",
    "3-bromothiophene": "3-溴噻吩",
    "3-buten-1-ol": "3-丁烯-1-醇",
    "3-butyn-1-ol": "3-丁炔-1-醇",
    "3-chloro-1-propanol": "3-氯-1-丙醇",
    "3-chloro-2-butanone": "3-氯-2-丁酮",
    "3-chloro-2-methyl-1-propene": "3-氯-2-甲基-1-丙烯",
    "3-chloro-4-fluorophenylboronic acid": "3-氯-4-氟苯硼酸",
    "3-chloro-4-methoxyaniline": "3-氯-4-甲氧基苯胺",
    "3-chloroperbenzoic acid (mcpba)": "3-氯過氧苯甲酸",
    "3-chlorophenylboronic acid": "3-氯苯硼酸",
    "3-decanone": "3-癸酮",
    "3-dimethylaminopropyl chloride hydrochloride": "3-二甲胺基丙基氯鹽酸鹽",
    "3-ethoxythiophene-2-boronic acid pinacol ester": "3-乙氧基噻吩-2-硼酸頻那醇酯",
    "3-fluoro-4-methoxyaniline": "3-氟-4-甲氧基苯胺",
    "3-fluorophenol": "3-氟苯酚",
    "3-hexylthiophene-2-boronic acid pinacol ester": "3-己基-2-噻吩硼酸頻那醇酯",
    "3-hydroxybenzoic acid": "3-羥基苯甲酸",
    "3-hydroxybutyric acid": "3-羥基丁酸",
    "3-iodobenzoic acid": "3-碘苯甲酸",
    "3-iodotoluene": "3-碘甲苯",
    "3-mercaptopropionic acid": "3-巰基丙酸",
    "3-methoxybenzoic acid": "3-甲氧基苯甲酸",
    "3-methoxythiophene-2-boronic acid pinacol ester": "3-甲氧基噻吩-2-硼酸頻那醇酯",
    "3-methyl-1-pentyn-3-ol": "3-甲基-1-戊炔-3-醇",
    "3-methyl-1-phenyl-5-pyrazolone": "3-甲基-1-苯基-5-吡唑酮",
    "3-methyl-2-butenal": "3-甲基-2-丁烯醛",
    "3-methyl-3-buten-1-ol": "3-甲基-3-丁烯-1-醇",
    "3-methyldiphenylamine": "3-甲基二苯胺",
    "3-methylpyridine": "3-甲基吡啶",
    "3-methylthiopropanaldehyde": "3-甲硫基丙醛",
    "3-nitrophenol": "3-硝基苯酚",
    "3-pyridinecarboxaldehyde": "3-吡啶甲醛",
    "3-pyridinemethanol": "3-吡啶甲醇",
    "3-thiopheneboronic acid": "3-噻吩硼酸",
    "3-thiophenecarboxaldehyde": "3-噻吩甲醛",
    "3-thiophenemethanol": "3-噻吩甲醇",
    "4'-(trifluoromethyl)-2-biphenylcarboxylic acid": "4'-",
    "4'-bromobenzo-15-crown-5": "4'-溴苯并-15-冠-5",
    "4'-hydroxybiphenyl-4-carboxylic acid": "4'-羥基聯苯-4-甲酸",
    "4'-methylacetophenone": "4'-甲基苯乙酮",
    "4,4'-(9-fluorenylidene)dianiline": "4,4'-",
    "4,4'-(9-fluorenylidene)diphenol": "4,4'-",
    "4,4'-(hexafluoroisopropylidene)diphthalic anhydride (6fda)": "4,4'-",
    "4,4'-bis(bromomethyl)biphenyl": "4,4'-雙",
    "4,4'-di-tert-butylbiphenyl": "4,4'-二叔丁基聯苯",
    "4,4'-diaminodiphenylamine sulfate": "4,4'-二胺基二苯胺硫酸鹽",
    "4,4'-dibromobenzil": "4,4'-二溴苯偶醯",
    "4,4'-dibromobenzophenone": "4,4'-二溴二苯甲酮",
    "4,4'-dibromobiphenyl": "4,4'-二溴聯苯",
    "4,4'-dihydroxybenzophenone": "4,4'-二羥基二苯甲酮",
    "4,4'-diiodobiphenyl": "4,4'-二碘聯苯",
    "4,4'-dimethoxybenzophenone": "4,4'-二甲氧基二苯甲酮",
    "4,4'-dimethoxydiphenylamine": "4,4'-二甲氧基二苯胺",
    "4,4'-dimethyl-2,2'-bipyridyl": "4,4'-二甲基-2,2'-聯吡啶",
    "4,4'-dimethylbenzophenone": "4,4'-二甲基二苯甲酮",
    "4,4'-dipyridylamine": "4,4'-二吡啶胺",
    "4,4'-trimethylenedipyridine": "4,4'-三亞甲基二吡啶",
    "4,4-dihexyl-4h-silolo[3,2-b:4,5-b']dithiophene (dts)": "4,4-二己基-4H-矽雜環戊二烯并[3,2-b:4,5-b']二噻吩",
    "4,5-bis(diphenylphosphino)-9,9-dimethylxanthene (xantphos)": "4,5-雙",
    "4,5-dibromo-o-xylene": "4,5-二溴鄰二甲苯",
    "4,5-dichlorophthalic acid": "4,5-二氯鄰苯二甲酸",
    "4,5-dichlorophthalic anhydride": "4,5-二氯鄰苯二甲酸酐",
    "4,5-difluorophthalic anhydride": "4,5-二氟鄰苯二甲酸酐",
    "4,5-dimethyl-2-nitroaniline": "4,5-二甲基-2-硝基苯胺",
    "4,5-dimethylthiazole": "4,5-二甲基噻唑",
    "4,7-dibromo-2,1,3-benzothiadiazole": "4,7-二溴-2,1,3-苯并噻二唑",
    "4,7-dibromo-5,6-difluoro-2,1,3-benzothiadiazole": "4,7-二溴-5,6-二氟-2,1,3-苯并噻二唑",
    "4-(1-pyrrolidinyl)pyridine": "4-",
    "4-(aminomethyl)pyridine": "4-",
    "4-(benzyloxy)phenol": "4-苄氧基苯酚",
    "4-(bromomethyl)benzonitrile": "4-",
    "4-(bromomethyl)phenylboronic acid": "4-",
    "4-(bromomethyl)phenylboronic acid pinacol ester": "4-",
    "4-(bromomethyl)pyridine hydrobromide": "4-溴甲基吡啶氫溴酸鹽",
    "4-(chloromethyl)phenyl acetate": "乙酸-4-",
    "4-(diethylamino)aniline": "4-",
    "4-(ethoxycarbonyl)phenylboronic acid": "4-",
    "4-(hydroxymethyl)phenylboronic acid": "4-",
    "4-(methylthio)aniline": "4-",
    "4-(methylthio)phenylboronic acid": "4-",
    "4-(trifluoromethyl)aniline": "4-",
    "4-(trifluoromethyl)benzyl bromide": "4-",
    "4-(trifluoromethyl)phenylboronic acid": "4-",
    "4-(trifluoromethyl)styrene": "4-",
    "4-(trimethoxysilyl)butyronitrile": "4-",
    "4-amino-1-butanol": "4-胺基-1-丁醇",
    "4-amino-tempo": "4-胺基-2,2,6,6-四甲基哌啶-1-氧基",
    "4-aminobenzoic acid": "4-胺基苯甲酸",
    "4-aminobenzonitrile": "4-胺基苯甲腈",
    "4-aminobenzotrifluoride": "4-胺基三氟甲苯",
    "4-aminobenzyl alcohol": "4-胺基苯甲醇",
    "4-aminobutyric acid": "4-胺基丁酸",
    "4-aminodiphenylamine": "4-胺基二苯胺",
    "4-aminophenol": "4-胺基苯酚",
    "4-aminothiophenol": "4-胺基苯硫酚",
    "4-biphenylmethanol": "4-聯苯甲醇",
    "4-bromo-1-butene": "4-溴-1-丁烯",
    "4-bromo-2,3,5,6-tetrafluoropyridine": "4-溴-2,3,5,6-四氟吡啶",
    "4-bromo-2,6-diethylaniline": "4-溴-2,6-二乙基苯胺",
    "4-bromo-2-chloroanisole": "4-溴-2-氯苯甲醚",
    "4-bromo-2-ethoxybenzaldehyde": "4-溴-2-乙氧基苯甲醛",
    "4-bromo-2-fluoroanisole": "4-溴-2-氟苯甲醚",
    "4-bromo-2-methylaniline": "4-溴-2-甲基苯胺",
    "4-bromo-3,5-difluoroaniline": "4-溴-3,5-二氟苯胺",
    "4-bromo-3-chloroanisole": "4-溴-3-氯苯甲醚",
    "4-bromo-3-fluoroanisole": "4-溴-3-氟苯甲醚",
    "4-bromo-3-nitrotoluene": "4-溴-3-硝基甲苯",
    "4-bromo-4'-methoxybiphenyl": "4-溴-4'-甲氧基聯苯",
    "4-bromo-o-xylene": "4-溴鄰二甲苯",
    "4-bromoacetophenone": "4-溴苯乙酮",
    "4-bromoaniline": "4-溴苯胺",
    "4-bromoanisole": "4-溴苯甲醚",
    "4-bromobenzaldehyde": "4-溴苯甲醛",
    "4-bromobenzenethiol": "4-溴苯硫酚",
    "4-bromobenzoic acid": "4-溴苯甲酸",
    "4-bromobenzonitrile": "4-溴苯甲腈",
    "4-bromobenzophenone": "4-溴二苯甲酮",
    "4-bromobenzoyl chloride": "4-溴苯甲醯氯",
    "4-bromobenzyl bromide": "4-溴苯甲基溴",
    "4-bromobutyronitrile": "4-溴丁腈",
    "4-bromobutyryl chloride": "4-溴丁醯氯",
    "4-bromodiphenyl ether": "4-溴二苯醚",
    "4-bromomethylphenylboronic acid pinacol ester": "4-溴甲基苯硼酸頻哪醇酯",
    "4-bromophenol": "4-溴苯酚",
    "4-bromophenyl trifluoromethyl sulfide": "4-溴苯基三氟甲基硫醚",
    "4-bromophenylacetic acid": "4-溴苯乙酸",
    "4-bromophenylboronic acid": "4-溴苯硼酸",
    "4-bromophthalic anhydride": "4-溴鄰苯二甲酸酐",
    "4-bromopyridine hydrochloride": "4-溴吡啶鹽酸鹽",
    "4-bromostyrene": "4-溴史泰烯",
    "4-bromothioanisole": "4-溴硫苯甲醚",
    "4-bromotoluene": "4-溴甲苯",
    "4-bromoveratrole": "4-溴黎蘆醚",
    "4-butylphenylboronic acid": "4-丁基苯硼酸",
    "4-carboxyphenylboronic acid": "4-羧基苯硼酸",
    "4-chloro-1,8-naphthalic anhydride": "4-氯-1,8-萘二甲酸酐",
    "4-chlorobenzaldehyde": "4-氯苯甲醛",
    "4-chlorophenyl methyl sulfone": "4-氯苯基甲基碸",
    "4-chlorophenylboronic acid": "4-氯苯硼酸",
    "4-cyanobenzaldehyde": "4-氰基苯甲醛",
    "4-cyanobenzoic acid": "4-氰基苯甲酸",
    "4-cyanophenol": "4-氰基苯酚",
    "4-diazodiphenylamine sulfate": "4-重氮二苯胺硫酸鹽",
    "4-dimethylaminopyridine": "4-二甲胺基吡啶",
    "4-dimethylaminopyridine (dmap)": "4-二甲胺基吡啶",
    "4-dodecylresorcinol": "4-十二烷基間苯二酚",
    "4-ethynylanisole": "4-乙炔基苯甲醚",
    "4-fluoroaniline": "4-氟苯胺",
    "4-fluorobenzaldehyde": "4-氟苯甲醛",
    "4-fluorobenzenesulfonyl chloride": "4-氟苯磺醯氯",
    "4-fluorobenzenethiol": "4-氟苯硫酚",
    "4-fluorobenzoic acid": "4-氟苯甲酸",
    "4-fluorobenzonitrile": "4-氟苯甲腈",
    "4-fluorobenzophenone": "4-氟二苯甲酮",
    "4-fluorobenzyl bromide": "4-氟溴化苄",
    "4-fluorobenzyl mercaptan": "4-氟苄硫醇",
    "4-fluoroiodobenzene": "4-氟碘苯",
    "4-fluorophenol": "4-氟苯酚",
    "4-fluorophenylboronic acid": "4-氟苯硼酸",
    "4-fluorophenylhydrazine hydrochloride": "4-氟苯肼鹽酸鹽",
    "4-formylphenylboronic acid": "4-甲醛基苯硼酸",
    "4-hexadecyloxybenzoic acid": "4-十六烷氧基苯甲酸",
    "4-hydroxy-1-naphthaldehyde": "4-羥基-1-萘甲醛",
    "4-hydroxy-2-butanone": "4-羥基-2-丁酮",
    "4-hydroxybenzeneboronic acid": "4-羥基苯硼酸",
    "4-hydroxybenzoic acid": "4-羥基苯甲酸",
    "4-hydroxybenzyl alcohol": "4-羥基苯甲醇",
    "4-hydroxyphenylboronic acid": "4-羥基苯硼酸",
    "4-hydroxypyridine": "4-羥基吡啶",
    "4-iodo-1,1,1-trifluorobutane": "4-碘-1,1,1-三氟丁烷",
    "4-iodo-m-xylene": "4-碘間二甲苯",
    "4-iodo-o-xylene": "4-碘鄰二甲苯",
    "4-iodoaniline": "4-碘苯胺",
    "4-iodoanisole": "4-碘苯甲醚",
    "4-iodobenzoic acid": "4-碘苯甲酸",
    "4-iodobenzonitrile": "4-碘苯甲腈",
    "4-iodophenol": "4-碘苯酚",
    "4-mercaptobenzoic acid": "4-巰基苯甲酸",
    "4-mercaptophenol": "4-巰基苯酚",
    "4-mercaptopyridine": "4-巰基吡啶",
    "4-methoxy-alpha-toluenethiol": "4-甲氧基-α-甲苯硫醇",
    "4-methoxybenzaldehyde": "4-甲氧基苯甲醛",
    "4-methoxybenzophenone": "4-甲氧基二苯甲酮",
    "4-methoxybenzyl chloride": "4-甲氧基苄基氯",
    "4-methoxybiphenyl": "4-甲氧基聯苯",
    "4-methoxyphenol": "4-甲氧基苯酚",
    "4-methoxyphenylboronic acid": "4-甲氧基苯硼酸",
    "4-methyl-2,3,5,6-tetrafluoropyridine": "4-甲基-2,3,5,6-四氟吡啶",
    "4-methylbenzeneboronic acid": "4-甲基苯硼酸",
    "4-methylbenzenesulfonic acid monohydrate": "對甲苯磺酸一水合物",
    "4-methylbenzyl bromide": "4-甲基苄基溴",
    "4-methylbenzyl mercaptan": "4-甲基苄硫醇",
    "4-methylesculetin": "4-甲基七葉亭",
    "4-methylmorpholine n-oxide": "N-甲基嗎啉-N-氧化物",
    "4-methylpyridine 1-oxide": "4-甲基吡啶-N-氧化物",
    "4-methylpyrrole-2-carboxylic acid methyl ester": "4-甲基吡咯-2-甲酸甲酯",
    "4-methylvaleric acid": "4-甲基戊酸",
    "4-nitro-1,8-naphthalic anhydride": "4-硝基-1,8-萘二甲酸酐",
    "4-nitrobenzeneboronic acid": "4-硝基苯硼酸",
    "4-nitrobenzenediazonium tetrafluoroborate": "4-硝基苯重氮四氟硼酸鹽",
    "4-nitrobenzenesulfonyl chloride": "4-硝基苯磺醯氯",
    "4-nitrobenzyl alcohol": "4-硝基苯甲醇",
    "4-nitrobenzyl bromide": "4-硝基溴化苄",
    "4-nitrophenol": "4-硝基苯酚",
    "4-nitrothiophenol": "4-硝基苯硫酚",
    "4-penten-1-ol": "4-戊烯-1-醇",
    "4-pentenenitrile": "4-戊烯腈",
    "4-pentenoic acid": "4-戊烯酸",
    "4-pentyn-1-ol": "4-戊炔-1-醇",
    "4-pentynoic acid": "4-戊炔酸",
    "4-phenylphenol": "4-苯基苯酚",
    "4-picoline": "4-甲基吡啶",
    "4-picolyl chloride hydrochloride": "4-吡啶甲基氯鹽酸鹽",
    "4-pyridinepropanol": "4-吡啶丙醇",
    "4-pyridinethiol": "4-巰基吡啶",
    "4-pyridinylboronic acid": "4-吡啶硼酸",
    "4-pyridylacetic acid": "4-吡啶乙酸",
    "4-pyridylcarbinol": "4-吡啶甲醇",
    "4-tert-butylbenzyl bromide": "4-叔丁基溴化苄",
    "4-tert-butylphenylboronic acid": "4-叔丁基苯硼酸",
    "4-tert-butylpyridine": "4-三級丁基吡啶",
    "4-tolylboronic acid": "4-甲基苯硼酸",
    "4-trimethylsilyl-3-butyn-1-ol": "4-三甲基矽基-3-丁炔-1-醇",
    "4-tritylphenol": "4-三苯甲基苯酚",
    "4-vinylanisole": "4-乙烯基苯甲醚",
    "4-vinylpyridine": "4-乙烯基吡啶",
    "4h-3,1-benzoxazine-2,4(1h)-dione": "靛紅酸酐",
    "4h-cyclopenta[2,1-b:3,4-b']dithiophen-4-one": "4H-環戊[2,1-b:3,4-b']二噻吩-4-酮",
    "4h-cyclopenta[2,1-b:3,4-b']dithiophene": "4H-環戊[2,1-b:3,4-b']二噻吩",
    "4h-dithieno[3,2-b:2',3'-d]pyrrole": "4H-二噻吩并[3,2-b:2',3'-d]吡咯",
    "5,10,15,20-tetraphenyl-21h,23h-porphine (tpp)": "5,10,15,20-四苯基卟啉",
    "5,11-dihydroindolo[3,2-b]carbazole": "5,11-二氫吲哚并[3,2-b]咔唑",
    "5,5''-dibromo-2,2':5',2''-terthiophene": "5,5''-二溴-2,2':5',2''-三噻吩",
    "5,6-dimethylbenzimidazole": "5,6-二甲基苯并咪唑",
    "5,7-diiodo-8-hydroxyquinoline": "5,7-二碘-8-羥基喹啉",
    "5-bromo-1,2,3-trifluorobenzene": "5-溴-1,2,3-三氟苯",
    "5-bromo-1,3-difluoro-2-iodobenzene": "5-溴-1,3-二氟-2-碘苯",
    "5-bromo-1-indanone": "5-溴-1-茚酮",
    "5-bromo-1-pentene": "5-溴-1-戊烯",
    "5-bromo-2,2'-bithiophene-5'-carboxaldehyde": "5-溴-2,2'-聯噻吩-5'-甲醛",
    "5-bromo-2-nitroanisole": "5-溴-2-硝基苯甲醚",
    "5-bromo-2-thiophenecarbaldehyde": "5-溴-2-噻吩甲醛",
    "5-bromo-2-thiophenecarboxaldehyde": "5-溴-2-噻吩甲醛",
    "5-bromo-m-xylene": "5-溴間二甲苯",
    "5-bromobenzo-1,3-dioxole": "5-溴-1,3-苯并戴奧辛",
    "5-bromopyridine-2-carbaldehyde": "5-溴吡啶-2-甲醛",
    "5-bromovaleryl chloride": "5-溴戊醯氯",
    "5-chloro-1,3,3-trimethyl-2-methyleneindoline": "5-氯-1,3,3-三甲基-2-亞甲基吲哚啉",
    "5-chloro-1-pentyne": "5-氯-1-戊炔",
    "5-formyl-2-thiopheneboronic acid": "5-甲醛基-2-噻吩硼酸",
    "5-formylthiophene-2-boronic acid": "5-甲醯基噻吩-2-硼酸",
    "5-hexen-1-ol": "5-己烯-1-醇",
    "5-hexenenitrile": "5-己烯腈",
    "5-hexyn-1-ol": "5-己炔-1-醇",
    "5-hexynoic acid": "5-己炔酸",
    "5-hydroxyisophthalic acid": "5-羥基間苯二甲酸",
    "5-iodo-m-xylene": "5-碘間二甲苯",
    "5-methylthiophene-2-boronic acid": "5-甲基噻吩-2-硼酸",
    "5-sulfosalicylic acid dihydrate": "5-磺基水楊酸二水合物",
    "5-tert-butylisophthalic acid": "5-叔丁基間苯二甲酸",
    "6,13-pentacenequinone": "6,13-並五苯醌",
    "6,6-dimethylfulvene": "6,6-二甲基富烯",
    "6-(methylthio)-1-hexanol": "6-",
    "6-bromohexanenitrile": "6-溴己腈",
    "6-bromohexanoic acid": "6-溴己酸",
    "6-bromohexanoyl chloride": "6-溴己醯氯",
    "6-chloro-1-hexene": "6-氯-1-己烯",
    "6-chlorohexan-1-ol": "6-氯-1-己醇",
    "6-heptenoic acid": "6-庚烯酸",
    "6-heptynoic acid": "6-庚炔酸",
    "6-methylbenzothiazol-2-ylamine": "2-胺基-6-甲基苯并噻唑",
    "6-methylpyridine-3-carbonitrile": "6-甲基吡啶-3-甲腈",
    "7,7,8,8-tetracyanoquinodimethane": "7,7,8,8-四氰基奎諾二甲烷",
    "7-bromo-1-heptanol": "7-溴-1-庚醇",
    "7-bromo-1-heptene": "7-溴-1-庚烯",
    "7-bromoheptanoic acid": "7-溴庚酸",
    "7-diethylamino-4-methylcoumarin": "7-二乙胺基-4-甲基香豆素",
    "7-hexadecyn-1-ol": "7-十六炔-1-醇",
    "7-octyn-1-ol": "7-辛炔-1-醇",
    "8-bromo-1-octanol": "8-溴-1-辛醇",
    "8-bromooctanoic acid": "8-溴辛酸",
    "8-hydroxyquinaldine": "8-羥基-2-甲基喹啉",
    "8-hydroxyquinoline": "8-羥基喹啉",
    "8-hydroxyquinoline-5-sulfonic acid": "8-羥基喹啉-5-磺酸",
    "8-mercaptooctanoic acid": "8-巰基辛酸",
    "8-methylquinoline": "8-甲基喹啉",
    "9(10h)-acridanone": "9-吖啶酮",
    "9,10-dihydroanthracene": "9,10-二氫蒽",
    "9,10-diphenylanthracene": "9,10-二苯基蒽",
    "9,9-bis(4-hydroxyphenyl)fluorene": "9,9-雙",
    "9,9-bis[4-(2-hydroxyethoxy)phenyl]fluorene": "9,9-雙[4-",
    "9-anthracenemethanol": "9-蒽甲醇",
    "9-bromophenanthrene": "9-溴菲",
    "9-decen-1-ol": "9-癸烯-1-醇",
    "9-dodecyn-1-ol": "9-十二炔-1-醇",
    "9-fluorenone": "9-芴酮",
    "[1,1'-bis(diphenylphosphino)ferrocene]dichloropalladium(ii)": "[1,1'-雙",
    "[1,1'-bis(diphenylphosphino)ferrocene]dichloropalladium(ii), complex with dichloromethane": "[1,1'-雙",
    "[1,2-bis(diphenylphosphino)ethane]dichloronickel(ii)": "[1,2-雙",
    "[1,3-bis(diphenylphosphino)propane]dichloronickel(ii)": "[1,3-雙",
    "acetaldehyde": "乙醛",
    "acetic acid": "醋酸",
    "acetic acid (glacial)": "冰醋酸",
    "acetic acid-d4": "醋酸-d4",
    "acetic anhydride": "醋酸酐",
    "acetone": "丙酮",
    "acetonitrile": "乙腈",
    "acetonitrile-d3": "乙腈-d3",
    "acetophenone": "苯乙酮",
    "acetylenedicarboxylic acid": "乙炔二甲酸",
    "acrolein dimer": "丙烯醛二聚體",
    "acrylic acid": "丙烯酸",
    "acrylonitrile": "丙烯腈",
    "acrylyl chloride": "丙烯醯氯",
    "active charcoal (activated carbon)": "活性碳",
    "aibn (2,2'-azobisisobutyronitrile)": "偶氮二異丁腈",
    "allyl bromide": "烯丙基溴",
    "allyltributyltin": "烯丙基三丁基錫",
    "allyltrichlorosilane": "烯丙基三氯矽烷",
    "alpha,alpha'-dibromo-o-xylene": "α,α'-二溴鄰二甲苯",
    "alpha,alpha'-dibromo-p-xylene": "α,α'-二溴對二甲苯",
    "alpha,alpha,alpha',alpha'-tetrabromo-o-xylene": "α,α,α',α'-四溴鄰二甲苯",
    "alpha,alpha,alpha-trifluoro-p-toluic acid": "α,α,α-三氟對甲苯甲酸",
    "alpha-bromo-para-toluic acid": "α-溴對甲苯甲酸",
    "alpha-d-glucose": "α-D-葡萄糖",
    "alpha-naphthyl acetate": "乙酸-α-萘酯",
    "alpha-terpinene": "α-萜品烯",
    "aluminium triisopropanolate": "異丙醇鋁",
    "aluminum chloride": "氯化鋁",
    "aluminum nitrate enneahydrate": "硝酸鋁九水合物",
    "aluminum oxide": "氧化鋁",
    "ammonia": "氨",
    "ammonium acetate": "醋酸銨",
    "ammonium chloride": "氯化銨",
    "ammonium fluoride": "氟化銨",
    "ammonium fluoroborate": "氟硼酸銨",
    "ammonium formate": "甲酸銨",
    "ammonium hexafluorophosphate": "六氟磷酸銨",
    "ammonium hexafluorotitanate": "六氟鈦酸銨",
    "ammonium hydroxide": "氫氧化銨",
    "ammonium hydroxide (aqua ammonia)": "氫氧化銨",
    "ammonium metavanadate": "偏釩酸銨",
    "ammonium persulfate (aps)": "過硫酸銨",
    "amyl nitrite": "亞硝酸戊酯",
    "aniline": "苯胺",
    "aniline hydrochloride": "苯胺鹽酸鹽",
    "anthracene": "蒽",
    "anthranilic acid": "鄰胺基苯甲酸",
    "anthraquinone": "蒽醌",
    "anthrone": "蒽酮",
    "arachidic acid": "花生酸",
    "arachidonic acid": "花生四烯酸",
    "au (gold)": "金",
    "azidotrimethylsilane": "疊氮三甲基矽烷",
    "azobisisobutyronitrile (aibn)": "偶氮二異丁腈",
    "azodiisobutyronitrile": "偶氮二異丁腈",
    "barium chloride": "氯化鋇",
    "barium hydroxide octahydrate": "氫氧化鋇八水合物",
    "behenic acid": "山嵛酸",
    "benzal chloride": "亞苄基二氯",
    "benzaldehyde": "苯甲醛",
    "benzamide": "苯甲醯胺",
    "benzanthrone": "苯并蒽酮",
    "benzene": "苯",
    "benzimidazole": "苯并咪唑",
    "benzo[b]thiophene": "苯并[b]噻吩",
    "benzoic acid": "苯甲酸",
    "benzonitrile": "苯甲腈",
    "benzophenone": "二苯甲酮",
    "benzophenone imine": "二苯甲酮亞胺",
    "benzoyl chloride": "苯甲醯氯",
    "benzoyl peroxide": "過氧化苯甲醯",
    "benzoyl peroxide (bpo)": "過氧化苯甲醯",
    "benzyl alcohol": "苯甲醇",
    "benzyl bromide": "溴化苄",
    "benzyl cyanide": "苯乙腈",
    "benzyl mercaptan": "苄硫醇",
    "benzylamine": "苄胺",
    "benzylphosphonic acid": "苄基膦酸",
    "benzyltrichlorosilane": "苄基三氯矽烷",
    "benzyltriethylammonium chloride (teba)": "苄基三乙基氯化銨",
    "benzyltrimethylammonium chloride": "芐基三甲基氯化銨",
    "beta-eudesmol": "β-桉葉醇",
    "beta-ionone": "β-紫羅蘭酮",
    "bicyclohexyl": "聯環己烷",
    "bindschedler's green leuco base": "賓斯切勒綠無色基",
    "biotin": "生物素",
    "biphenyl": "聯苯",
    "biphenyl-4-carboxylic acid": "4-聯苯甲酸",
    "bis(benzonitrile)palladium(ii) chloride": "雙",
    "bis(cyclopentadienyl)zirconium(iv) dichloride": "二氯二茂鋯",
    "bis(dibenzylideneacetone)palladium(0)": "雙",
    "bis(dimethylamido)phosphoric chloride": "雙",
    "bis(phenylsulfonyl)sulfide": "雙",
    "bis(pinacolato)diboron": "雙",
    "bis(tri-tert-butylphosphine)palladium(0)": "雙",
    "bis(trichlorosilyl)methane": "雙",
    "bis(trifluoromethane)sulfonimide lithium salt": "雙",
    "bis(triphenylphosphine)palladium(ii) dichloride": "雙",
    "bis[(2-diphenylphosphino)phenyl] ether (dpephos)": "雙[",
    "bismuth(iii) nitrate pentahydrate": "硝酸鉍五水合物",
    "borane-tetrahydrofuran complex": "硼烷-四氫呋喃錯合物",
    "bornyl acetate": "乙酸龍腦酯",
    "boron tribromide": "三溴化硼",
    "boron trifluoride diethyl etherate": "三氟化硼乙醚錯合物",
    "boron trifluoride etherate": "三氟化硼乙醚錯合物",
    "bromine": "溴",
    "bromoacetonitrile": "溴乙腈",
    "bromobenzene": "溴苯",
    "bromoethane": "溴乙烷",
    "bromoform": "溴仿",
    "bromohydroquinone": "溴對苯二酚",
    "bromopentafluorobenzene": "溴五氟苯",
    "bromotrimethylsilane": "溴三甲基矽烷",
    "butyl isocyanatoacetate": "異氰酸乙酸丁酯",
    "butylamine": "正丁胺",
    "butylated hydroxyanisole (bha)": "丁基羥基甲氧苯",
    "butylated hydroxytoluene": "丁基羥基甲苯",
    "butylbenzene": "丁基苯",
    "butyllithium": "正丁基鋰",
    "butyric acid": "丁酸",
    "butyryl chloride": "丁醯氯",
    "cacodylic acid": "二甲胂酸",
    "calcium": "鈣",
    "calcium carbonate": "碳酸鈣",
    "calcium chloride": "氯化鈣",
    "calcium hydride": "氫化鈣",
    "calcium hydroxide": "氫氧化鈣",
    "calcium nitrate tetrahydrate": "硝酸鈣四水合物",
    "calcium sulfate (drierite)": "硫酸鈣",
    "calcium sulfate dihydrate (gypsum)": "硫酸鈣二水合物",
    "caproic acid": "己酸",
    "carbazole": "咔唑",
    "carbon disulfide": "二硫化碳",
    "carbon tetrabromide": "四溴化碳",
    "catechol": "鄰苯二酚",
    "catechol (1,2-dihydroxybenzene)": "鄰苯二酚",
    "catecholborane": "兒茶酚硼烷",
    "cedryl acetate": "乙酸柏木酯",
    "cerium ammonium nitrate (can)": "硝酸鈰銨",
    "cerium(iii) chloride heptahydrate": "氯化",
    "cerium(iii) nitrate hexahydrate": "硝酸",
    "cerium(iv) sulfate": "硫酸鈰",
    "cerium(iv) sulfate hydrate": "硫酸鈰",
    "cerotic acid": "蠟酸",
    "cesium azide": "疊氮化銫",
    "cesium carbonate": "碳酸銫",
    "cesium fluoride": "氟化銫",
    "cesium iodide": "碘化銫",
    "cetyltrimethylammonium bromide": "十六烷基三甲基溴化銨",
    "chloral hydrate": "水合氯醛",
    "chloro(cyclopentadienyl)bis(triphenylphosphine)ruthenium(ii)": "氯",
    "chloroacetyl chloride": "氯乙醯氯",
    "chlorobenzene": "氯苯",
    "chlorodifluoroacetic acid": "氯二氟乙酸",
    "chloroform": "氯仿",
    "chloroform-d": "氘代氯仿",
    "chloroplatinic acid hydrate": "氯鉑酸水合物",
    "chlorosulphonic acid": "氯磺酸",
    "chlorotris(triphenylphosphine)rhodium(i)": "氯化三",
    "choline": "膽鹼",
    "chromium trioxide": "三氧化鉻",
    "chromium(iii) chloride": "氯化鉻",
    "cinnamaldehyde": "肉桂醛",
    "cis-11-hexadecenal": "順-11-十六烯醛",
    "cis-11-hexadecenol": "順-11-十六烯醇",
    "cis-2-hexenol": "順-2-己烯醇",
    "cis-7,8-epoxy-2-methyloctadecane": "順-7,8-環氧-2-甲基十八烷",
    "cis-9, trans-11-tetradecadienyl acetate": "順-9,反-11-十四碳二烯乙酸酯",
    "cis-cyclooctene": "順-環辛烯",
    "citral": "檸檬醛",
    "citric acid": "檸檬酸",
    "citric acid monohydrate": "檸檬酸一水合物",
    "cobalt carbonyl": "羰基鈷",
    "cobalt(ii) carbonate": "碳酸鈷",
    "cobalt(ii) chloride": "氯化鈷",
    "cobalt(ii) phthalocyanine": "酞菁鈷",
    "copper dibromide": "溴化銅",
    "copper foil": "銅箔",
    "copper phthalocyanine": "酞菁銅",
    "copper powder": "銅粉",
    "copper sulfate": "硫酸銅",
    "copper(i) bromide": "溴化亞銅",
    "copper(i) chloride": "氯化亞銅",
    "copper(i) cyanide": "氰化亞銅",
    "copper(i) iodide": "碘化亞銅",
    "copper(i) iodide (cui)": "碘化亞銅",
    "copper(i) oxide": "氧化亞銅",
    "copper(ii) acetate": "醋酸銅",
    "copper(ii) acetate monohydrate": "醋酸銅一水合物",
    "copper(ii) acetylacetonate": "乙醯丙酮銅",
    "copper(ii) bromide": "溴化銅",
    "copper(ii) carbonate basic": "鹼式碳酸銅",
    "copper(ii) chloride": "氯化銅",
    "copper(ii) chloride dihydrate": "氯化銅",
    "copper(ii) nitrate hemipentahydrate": "硝酸銅半五水合物",
    "copper(ii) nitrate trihydrate": "硝酸銅三水合物",
    "copper(ii) sulfate (anhydrous)": "硫酸銅",
    "copper(ii) sulfate pentahydrate": "硫酸銅五水合物",
    "copper(ii) trifluoromethanesulfonate": "三氟甲磺酸銅",
    "corannulene": "碗烯",
    "coronene": "暈苯",
    "coumarin 6": "香豆素 6",
    "crotononitrile": "巴豆腈",
    "cyanoacetic acid": "氰乙酸",
    "cycloheptyl bromide": "溴環庚烷",
    "cyclohexane": "環己烷",
    "cyclohexanol": "環己醇",
    "cyclopropylacetylene": "環丙基乙炔",
    "cyjohnphos": "CyJohnPhos",
    "cysteamine": "半胱胺",
    "cysteamine hydrochloride": "半胱胺鹽酸鹽",
    "d-glucose (dextrose)": "D-葡萄糖",
    "dansyl chloride": "丹醯氯",
    "ddq": "2,3-二氯-5,6-二氰基-1,4-苯醌",
    "decanal": "癸醛",
    "decane": "正癸烷",
    "deuterium oxide": "氧化氘",
    "deuterium oxide (heavy water)": "氧化氘",
    "di(ethylene glycol)": "二甘醇",
    "di(propylene glycol) methyl ether": "二丙二醇甲醚",
    "di-n-butyltin dilaurate": "二月桂酸二丁基錫",
    "di-tert-butyl dicarbonate (boc anhydride)": "二-三級丁基焦碳酸酯",
    "diazald-n-methyl-d3": "N-甲基-d3-N-亞硝基對甲苯磺醯胺",
    "dibenzosuberenone": "二苯并環庚烯酮",
    "dibenzosuberone": "二苯并環庚酮",
    "dibenzothiophene": "二苯并噻吩",
    "dibenzyl malonate": "丙二酸二苄酯",
    "dibutyl sulfide": "二丁基硫醚",
    "dibutyldichlorosilane": "二丁基二氯矽烷",
    "dichloro(p-cymene)ruthenium(ii) dimer": "二氯",
    "dichloroacetic acid": "二氯乙酸",
    "dicyclohexano-18-crown-6": "二環己基-18-冠-6",
    "didodecyldimethylammonium bromide": "雙十二烷基二甲基溴化銨",
    "diethyl (3-bromopropyl)phosphonate": "(3-溴丙基)膦酸二乙酯",
    "diethyl (4-bromobutyl)phosphonate": "(4-溴丁基)膦酸二乙酯",
    "diethyl (bromomethyl)phosphonate": "(溴甲基)膦酸二乙酯",
    "diethyl 2,5-dibromoterephthalate": "2,5-二溴對苯二甲酸二乙酯",
    "diethyl 2-bromoethylphosphonate": "2-溴乙基膦酸二乙酯",
    "diethyl acetylenedicarboxylate": "乙炔二甲酸二乙酯",
    "diethyl azodicarboxylate": "偶氮二甲酸二乙酯",
    "diethyl benzylphosphonate": "苄基膦酸二乙酯",
    "diethyl chlorophosphate": "氯磷酸二乙酯",
    "diethyl cyanomethylphosphonate": "氰甲基膦酸二乙酯",
    "diethyl iodomethylphosphonate": "碘甲基膦酸二乙酯",
    "diethyl isopropylmalonate": "異丙基丙二酸二乙酯",
    "diethyl maleate": "馬來酸二乙酯",
    "diethyl phosphite": "亞磷酸二乙酯",
    "diethylamine": "二乙胺",
    "diethylenetriamine": "二乙烯三胺",
    "diethylzinc": "二乙基鋅",
    "diiodomethane": "二碘甲烷",
    "diisobutylaluminum hydride": "二異丁基氫化鋁",
    "diisobutylaluminum hydride (dibal-h)": "氫化二異丁基鋁",
    "diisopropylamine": "二異丙胺",
    "dimethyl (acetylmethyl)phosphonate": "(乙醯甲基)膦酸二甲酯",
    "dimethyl 2-thioxo-1,3-dithiole-4,5-dicarboxylate": "2-硫-1,3-二硫茂-4,5-二羧酸二甲酯",
    "dimethyl 5-aminoisophthalate": "5-胺基間苯二甲酸二甲酯",
    "dimethyl acetylenedicarboxylate": "乙炔二甲酸二甲酯",
    "dimethyl carbonate": "碳酸二甲酯",
    "dimethyl fumarate": "富馬酸二甲酯",
    "dimethyl phosphonate": "亞磷酸二甲酯",
    "dimethyl sulfide": "二甲基硫醚",
    "dimethyl sulfolane": "二甲基環丁碸",
    "dimethyl sulfoxide (dmso)": "二甲基亞碸",
    "dimethyl sulfoxide-d6 (dmso-d6)": "二甲基亞碸-d6",
    "dimethylamine hydrochloride": "二甲胺鹽酸鹽",
    "dimethylchlorosilane": "二甲基氯矽烷",
    "dimethyldichlorosilane": "二甲基二氯矽烷",
    "dimethylsiloxane copolymer": "二甲基矽氧烷共聚物",
    "dimethylthiocarbamoyl chloride": "二甲基硫代胺基甲醯氯",
    "dioctyl sodium sulfosuccinate": "二辛基磺基琥珀酸鈉",
    "dioctyl sulfide": "二辛基硫醚",
    "diphenyl ether": "二苯醚",
    "diphenyl phosphonate": "亞磷酸二苯酯",
    "diphenylacetic acid": "二苯乙酸",
    "diphenylacetylene": "二苯乙炔",
    "diphenylamine": "二苯胺",
    "diphenylmethane": "二苯甲烷",
    "disodium hydrogen phosphate": "磷酸氫二鈉",
    "disodium hydrogen phosphate dihydrate": "磷酸氫二鈉二水合物",
    "dithieno[3,2-b:2',3'-d]thiophene": "二噻吩并[3,2-b:2',3'-d]噻吩",
    "dl-2-methylbutyryl chloride": "DL-2-甲基丁醯氯",
    "dl-dithiothreitol": "DL-二硫蘇糖醇",
    "dmso (dimethyl sulfoxide)": "二甲基亞碸",
    "dodecanoic acid (lauric acid)": "十二酸",
    "dodecyl acetate": "乙酸十二酯",
    "dodecyl methyl sulfide": "十二烷基甲基硫醚",
    "erucic acid": "芥酸",
    "ethanol": "乙醇",
    "ethanolamine": "乙醇胺",
    "ethanolamine hydrochloride": "乙醇胺鹽酸鹽",
    "ethyl 4-aminobenzoate (benzocaine)": "4-胺基苯甲酸乙酯",
    "ethyl 4-bromobenzoate": "4-溴苯甲酸乙酯",
    "ethyl 4-bromobutyrate": "4-溴丁酸乙酯",
    "ethyl 4-bromocrotonate": "4-溴巴豆酸乙酯",
    "ethyl 4-pyridylacetate": "4-吡啶乙酸乙酯",
    "ethyl 5-amino-1-phenyl-4-pyrazolecarboxylate": "5-胺基-1-苯基-4-吡唑甲酸乙酯",
    "ethyl acetate": "乙酸乙酯",
    "ethyl acrylate": "丙烯酸乙酯",
    "ethyl anthranilate": "鄰胺基苯甲酸乙酯",
    "ethyl bromide": "溴乙烷",
    "ethyl carbamate (urethane)": "氨基甲酸乙酯",
    "ethyl chloroformate": "氯甲酸乙酯",
    "ethyl cyanoacetate": "氰乙酸乙酯",
    "ethyl ether": "乙醚",
    "ethyl isovalerate": "異戊酸乙酯",
    "ethyl mercaptan": "乙硫醇",
    "ethyl mercaptoacetate": "巰基乙酸乙酯",
    "ethyl methyl sulfide": "乙基甲基硫醚",
    "ethyl orthoformate (triethyl orthoformate)": "原甲酸三乙酯",
    "ethyl phenyl sulfone": "乙基苯基碸",
    "ethyl phenylpropiolate": "苯丙炔酸乙酯",
    "ethylamine": "乙胺",
    "ethylene glycol": "乙二醇",
    "ethylenediamine": "乙二胺",
    "ethylenediaminetetraacetic dianhydride": "乙二胺四乙酸二酐",
    "europium": "銪",
    "ferric chloride, anhydrous": "氯化鐵",
    "ferrocene": "二鐵",
    "florisil (magnesium silicate)": "矽酸鎂",
    "fluorene": "芴",
    "fluorobenzene": "氟苯",
    "fluoroboric acid": "氟硼酸",
    "fmoc-cys(trt)-oh": "Fmoc-S-三苯甲基-L-半胱胺酸",
    "fmoc-leu-oh": "Fmoc-L-白胺酸",
    "fmoc-trp(boc)-oh": "Fmoc-N-叔丁氧羰基-L-色胺酸",
    "formamide": "甲醯胺",
    "formamidine acetate": "甲脒醋酸鹽",
    "formamidinium iodide (fai)": "甲脒碘化銨",
    "formic acid": "甲酸",
    "fullerene-c60": "富勒烯 C60",
    "fumaric acid": "富馬酸",
    "furan": "呋喃",
    "gadolinium(iii) nitrate": "硝酸釓",
    "gamma-butyrolactone": "γ-丁內酯",
    "geraniol": "香葉醇",
    "glutaraldehyde": "戊二醛",
    "glycerol": "甘油",
    "glycerol (glycerin)": "甘油",
    "glycinamide hydrochloride": "甘胺醯胺鹽酸鹽",
    "glycine": "甘胺酸",
    "glycolonitrile": "乙醇腈",
    "gold trichloride": "三氯化金",
    "gold(iii) chloride trihydrate": "氯金酸三水合物",
    "gold(iii) chloride trihydrate (hydrogen tetrachloroaurate)": "氯金酸三水合物",
    "graphite": "石墨",
    "graphite powder": "石墨粉",
    "graphite, amorphous": "無定形石墨",
    "guanidine hydrochloride": "鹽酸胍",
    "halocarbon oil 700": "氟碳油 700",
    "heptacosafluorotetradecanoic acid": "全氟十四酸",
    "heptafluorobutyric acid": "七氟丁酸",
    "heptanoic acid": "庚酸",
    "hesperidin": "橙皮苷",
    "hexa-n-butylditin": "六正丁基二錫",
    "hexabutyldistannane": "六丁基二錫",
    "hexacosane": "二十六烷",
    "hexadecanedioic acid": "十六烷二酸",
    "hexadecyltrichlorosilane": "十六烷基三氯矽烷",
    "hexadecyltrimethylammonium bromide (ctab)": "十六烷基三甲基溴化銨",
    "hexafluoroacetone trihydrate": "六氟丙酮三水合物",
    "hexafluorobenzene": "六氟苯",
    "hexamethyldisilathiane": "六甲基二矽硫烷",
    "hexamethyldisilazane": "六甲基二矽氮烷",
    "hexamethyldisilazane (hmds)": "六甲基二矽氮烷",
    "hexamethyldisiloxane": "六甲基二矽氧烷",
    "hexamethylditin": "六甲基二錫",
    "hexamethylphosphoramide (hmpa)": "六甲基磷醯胺",
    "hexamethylphosphorous triamide (hmpt)": "六甲基亞磷酸三醯胺",
    "hexane": "正己烷",
    "hexanoyl chloride": "己醯氯",
    "hexylamine": "正己胺",
    "hexyltrichlorosilane": "己基三氯矽烷",
    "histamine": "組織胺",
    "hydramethylnon": "伏蟻腙",
    "hydrazine hydrate": "水合聯氨",
    "hydrazine monohydrate": "水合聯氨",
    "hydrazine monohydrate (note: cas 865-49-6 is typically chloroform-d)": "水合聯氨",
    "hydriodic acid": "氫碘酸",
    "hydrochloric acid": "鹽酸",
    "hydrogen bromide": "溴化氫",
    "hydrogen fluoride pyridine complex (olah's reagent)": "氟化氫吡啶錯合物",
    "hydrogen peroxide": "過氧化氫",
    "hydrogen tetrachloroaurate(iii) hydrate": "四氯金酸",
    "hydroquinone": "對苯二酚",
    "hydroxyacetic acid": "羥基乙酸",
    "hydroxylamine hydrochloride": "鹽酸羥胺",
    "hydroxylamine sulfate": "硫酸羥胺",
    "imidazole": "咪唑",
    "indol-5-yl methyl ether (5-methoxyindole)": "5-甲氧基吲哚",
    "indole": "吲哚",
    "iodic acid": "碘酸",
    "iodine": "碘",
    "iodine monochloride": "一氯化碘",
    "iodobenzene": "碘苯",
    "iodopentafluorobenzene": "五氟碘苯",
    "iodosobenzene diacetate": "二乙酸碘苯",
    "iodotrimethylsilane": "碘三甲基矽烷",
    "ion-exchange resin": "離子交換樹脂",
    "iridium chloride hydrate": "氯化銥水合物",
    "iron": "鐵",
    "iron chloride, hexahydrate": "氯化鐵六水合物",
    "iron(ii) chloride tetrahydrate": "氯化亞鐵四水合物",
    "iron(iii) acetylacetonate": "乙醯丙酮鐵",
    "iron(iii) chloride (anhydrous)": "氯化鐵",
    "isoamyl alcohol": "異戊醇",
    "isoamyl sulfide": "異戊基硫醚",
    "isobutyl acetate": "乙酸異丁酯",
    "isobutyl chloroformate": "氯甲酸異丁酯",
    "isobutyryl chloride": "異丁醯氯",
    "isocytosine": "異胞嘧啶",
    "isonicotinic acid": "異菸鹼酸",
    "isoprene": "異戊二烯",
    "isopropyl alcohol (ipa)": "異丙醇",
    "isopropylidene malonate": "亞異丙基丙二酸",
    "isopropylmagnesium bromide": "異丙基溴化鎂",
    "isopropylmagnesium chloride": "異丙基氯化鎂",
    "isovaleraldehyde": "異戊醛",
    "isovaleryl chloride": "異戊醯氯",
    "isoviolanthrone": "異維奧蒽酮",
    "l-2,4-diaminobutyric acid dihydrochloride": "L-2,4-二胺基丁酸二鹽酸鹽",
    "l-alanine methyl ester hydrochloride": "L-丙胺酸甲酯鹽酸鹽",
    "l-ascorbic acid": "L-抗壞血酸",
    "l-aspartic acid": "L-天門冬胺酸",
    "l-glutamic acid gamma-benzyl ester": "L-麩胺酸-γ-苄酯",
    "l-lysine methyl ester dihydrochloride": "L-離胺酸甲酯二鹽酸鹽",
    "l-proline": "L-脯胺酸",
    "lanthanum nitrate hexahydrate": "硝酸鑭六水合物",
    "lanthanum(iii) chloride heptahydrate": "氯化鑭七水合物",
    "lauric acid": "月桂酸",
    "lauroyl chloride": "月桂醯氯",
    "lavandulyl acetate": "乙酸薰衣草酯",
    "lavender oil": "薰衣草油",
    "lawesson's reagent": "勞森試劑",
    "lead tetraacetate": "四乙酸鉛",
    "lead(ii) bromide": "溴化鉛",
    "lead(ii) chloride": "氯化鉛",
    "lead(ii) fluoride": "氟化鉛",
    "lead(ii) iodide": "碘化鉛",
    "lemongrass oil": "檸檬草油",
    "lithium acetylide ethylenediamine complex": "乙炔鋰乙二胺錯合物",
    "lithium aluminum deuteride (liald4)": "氘代氫化鋁鋰",
    "lithium aluminum hydride": "氫化鋁鋰",
    "lithium aluminum hydride (lah)": "氫化鋁鋰",
    "lithium aluminum tri-tert-butoxyhydride": "三叔丁氧基氫化鋁鋰",
    "lithium amide": "胺基鋰",
    "lithium bis(trimethylsilyl)amide": "雙",
    "lithium borohydride": "硼氫化鋰",
    "lithium carbonate": "碳酸鋰",
    "lithium chloride": "氯化鋰",
    "lithium diisopropylamide": "二異丙基胺基鋰",
    "lithium hydroxide monohydrate": "氫氧化鋰一水合物",
    "lithium iodide": "碘化鋰",
    "m-phenylenediamine": "間苯二胺",
    "m-toluidine": "間-甲苯胺",
    "m-tolylboronic acid": "間甲基苯硼酸",
    "magnesium bromide ethyl etherate": "溴化鎂乙醚錯合物",
    "magnesium nitrate hexahydrate": "硝酸鎂六水合物",
    "magnesium powder": "鎂粉",
    "magnesium sulfate heptahydrate": "硫酸鎂七水合物",
    "maleic anhydride": "馬來酸酐",
    "maleimide": "馬來醯亞胺",
    "malonic acid": "丙二酸",
    "malononitrile": "丙二腈",
    "mandelonitrile": "苯乙醇腈",
    "manganese dioxide": "二氧化錳",
    "manganese(ii) acetate tetrahydrate": "醋酸錳",
    "manganese(ii) carbonate": "碳酸錳",
    "manganese(ii) chloride tetrahydrate": "氯化錳四水合物",
    "manganese(ii) nitrate": "硝酸錳",
    "mercuric oxide (red)": "氧化汞",
    "mercury": "汞",
    "mercury(ii) acetate": "醋酸汞",
    "mes hydrate": "MES 水合物",
    "mesitylboronic acid": "均三甲苯硼酸",
    "mesitylene": "均三甲苯",
    "methanesulfonic acid": "甲磺酸",
    "methanol-d4": "甲醇-d4",
    "methyl 3-(bromomethyl)benzoate": "3-",
    "methyl 3-bromobenzoate": "3-溴苯甲酸甲酯",
    "methyl 4-iodobenzoate": "4-碘苯甲酸甲酯",
    "methyl acetate": "醋酸甲酯",
    "methyl alcohol (methanol)": "甲醇",
    "methyl anthranilate": "鄰氨基苯甲酸甲酯",
    "methyl benzoate": "苯甲酸甲酯",
    "methyl crotonate": "巴豆酸甲酯",
    "methyl ethyl ketone": "甲乙酮",
    "methyl ethyl ketone (mek)": "甲乙酮",
    "methyl iodide (iodomethane)": "碘甲烷",
    "methyl malonyl chloride": "甲基丙二酸單氯",
    "methyl propiolate": "丙炔酸甲酯",
    "methyl salicylate": "水楊酸甲酯",
    "methyl stearate": "硬脂酸甲酯",
    "methylal": "甲縮醛",
    "methylamine": "甲胺",
    "methylamine anhydrous": "甲胺",
    "methylamine hydrochloride": "甲胺鹽酸鹽",
    "methylammonium bromide": "甲基溴化銨",
    "methylammonium iodide": "甲基碘化銨",
    "methylammonium thiocyanate": "甲基硫氰酸銨",
    "methyllithium": "甲基鋰",
    "methylmagnesium bromide": "甲基溴化鎂",
    "methylmorpholine": "N-甲基嗎啉",
    "methyltrioctylammonium chloride (aliquat 336)": "甲基三辛基氯化銨",
    "mineral oil": "礦物油",
    "molecular sieves": "分子篩",
    "molybdenum trioxide": "三氧化鉬",
    "myristoyl chloride": "肉豆蔻醯氯",
    "myristyl acetate": "乙酸肉豆蔻酯",
    "n,n'-carbonyldiimidazole (cdi)": "N,N'-碳二亞胺唑",
    "n,n'-dicyclohexylcarbodiimide (dcc)": "N,N'-二環己基碳二亞胺",
    "n,n'-diisopropylcarbodiimide": "N,N'-二異丙基碳二亞胺",
    "n,n'-diisopropylcarbodiimide (dic)": "N,N'-二異丙基碳二亞胺",
    "n,n'-diphenylbenzidine": "N,N'-二苯基聯苯胺",
    "n,n,n'-trimethylethylenediamine": "N,N,N'-三甲基乙二胺",
    "n,n-diethylaniline": "N,N-二乙基苯胺",
    "n,n-diisopropylethylamine": "N,N-二異丙基乙胺",
    "n,n-dimethyl-1,4-phenylenediamine": "N,N-二甲基-1,4-苯二胺",
    "n,n-dimethylacetamide (dmac)": "N,N-二甲基乙醯胺",
    "n,n-dimethylformamide": "二甲基甲醯胺",
    "n,n-dimethylformamide (dmf)": "N,N-二甲基甲醯胺",
    "n-[3-(trimethoxysilyl)propyl]aniline": "N-[3-",
    "n-alpha,n-alpha-bis(carboxymethyl)-l-lysine": "Nα,Nα-雙",
    "n-amyl sulfide": "二戊基硫醚",
    "n-bromosuccinimide (nbs)": "N-溴代丁二醯亞胺",
    "n-butyldiethanolamine": "N-丁基二乙醇胺",
    "n-butyllithium": "正丁基鋰",
    "n-chlorosuccinimide": "N-氯代琥珀醯亞胺",
    "n-chlorosuccinimide (ncs)": "N-氯代丁二醯亞胺",
    "n-cyclohexylmaleimide": "N-環己基馬來醯亞胺",
    "n-dodecanoyl chloride": "月桂醯氯",
    "n-dodecanoyl chloride (lauroyl chloride)": "十二醯氯",
    "n-heptyl methyl sulfide": "甲基庚基硫醚",
    "n-hexadecane": "正十六烷",
    "n-hexylbenzene": "正己基苯",
    "n-hydroxysuccinimide (nhs)": "N-羥基琥珀醯亞胺",
    "n-iodosuccinimide": "N-碘代琥珀醯亞胺",
    "n-iodosuccinimide (nis)": "N-碘代丁二醯亞胺",
    "n-methyl-2-pyrrolidone (nmp)": "N-甲基-2-吡咯烷酮",
    "n-methyl-n-(p-tolylsulfonyl)nitrosamide": "N-甲基-N-亞硝基對甲苯磺醯胺",
    "n-methyldicyclohexylamine": "N-甲基二環己胺",
    "n-methylformanilide": "N-甲基甲醯苯胺",
    "n-methyliminodiacetic acid": "N-甲基亞胺二醋酸",
    "n-methylpyrrole": "N-甲基吡咯",
    "n-methylpyrrolidinone": "N-甲基吡咯烷酮",
    "n-phenyl-1,4-phenylenediamine": "N-苯基-1,4-苯二胺",
    "n-phenyl-1-naphthylamine": "N-苯基-1-萘胺",
    "n-phenylanthranilic acid": "N-苯基鄰胺基苯甲酸",
    "n-phenylmaleimide": "N-苯基馬來醯亞胺",
    "n-propyltriethoxysilane": "正丙基三乙氧基矽烷",
    "n1,n2-bis(4-hydroxy-2,6-dimethylphenyl)oxalamide": "N1,N2-雙",
    "n1,n2-di-tert-butylethane-1,2-diamine": "N,N'-二-三級丁基乙二胺",
    "n719": "N719 染料",
    "n719 dye (ruthenium dye)": "N719 染料",
    "naphthalene": "萘",
    "naphthalene-1-boronic acid": "1-萘硼酸",
    "naphthalene-2-boronic acid": "2-萘硼酸",
    "naphtho[1,2-b:5,6-b']dithiophene": "萘并[1,2-b:5,6-b']二噻吩",
    "neodymium(iii) nitrate hexahydrate": "硝酸釹",
    "nerolidol": "橙花叔醇",
    "nickel(ii) acetate tetrahydrate": "醋酸鎳四水合物",
    "nickel(ii) bromide": "溴化鎳",
    "nickel(ii) chloride hexahydrate": "氯化鎳",
    "nickel(ii) formate dihydrate": "甲酸鎳二水合物",
    "nickel(ii) nitrate hexahydrate": "硝酸鎳",
    "ninhydrin": "茚三酮",
    "nitric acid": "硝酸",
    "nitrobenzene": "硝基苯",
    "nitroethane": "硝基乙烷",
    "nitromethane": "硝基甲烷",
    "nonanal": "壬醛",
    "norbornadiene rhodium(i) chloride dimer": "降冰片二烯氯化銠",
    "o-anisidine": "鄰甲氧基苯胺",
    "o-bromobenzaldehyde": "鄰-溴苯甲醛",
    "o-dichlorobenzene": "鄰二氯苯",
    "o-phenylenediamine": "鄰苯二胺",
    "o-phthalaldehyde": "鄰苯二甲醛",
    "o-terphenyl": "鄰-三聯苯",
    "o-toluidine": "鄰-甲苯胺",
    "o-xylene": "鄰二甲苯",
    "octadecyltrichlorosilane": "十八烷基三氯矽烷",
    "octadecyltrichlorosilane (ots)": "十八烷基三氯矽烷",
    "octafluorocyclopentene": "八氟環戊烯",
    "octane": "辛烷",
    "octylbenzene": "辛基苯",
    "octyltrichlorosilane": "辛基三氯矽烷",
    "oleylamine": "油胺",
    "osmium tetroxide": "四氧化鋨",
    "oxalic acid dihydrate": "草酸二水合物",
    "oxalyl chloride": "草醯氯",
    "p-anisic acid": "對茴香酸",
    "p-anisidine": "對-甲氧基苯胺",
    "p-chloranil": "四氯對苯醌",
    "p-cresol": "對甲酚",
    "p-fluorobromobenzene": "對氟溴苯",
    "p-nitroaniline": "對硝基苯胺",
    "p-nitrophenol": "對硝基苯酚",
    "p-nitrotoluene": "對硝基甲苯",
    "p-phenylbenzaldehyde": "4-聯苯甲醛",
    "p-phenylene diisocyanate": "對苯二異氰酸酯",
    "p-phenylenediamine": "對苯二胺",
    "p-sexiphenyl": "對六聯苯",
    "p-terphenyl": "對-三聯苯",
    "p-thiocresol": "對硫甲酚",
    "p-tolualdehyde": "對甲苯甲醛",
    "p-toluenesulfonic acid": "對甲苯磺酸",
    "p-toluenesulfonic acid monohydrate": "對甲苯磺酸一水合物",
    "p-toluenesulfonyl azide": "對甲苯磺醯疊氮",
    "p-toluenesulfonyl chloride": "對甲苯磺醯氯",
    "p-toluenesulfonyl chloride (tosyl chloride)": "對甲苯磺醯氯",
    "p-tolunitrile": "對甲基苯甲腈",
    "p-tolylmagnesium bromide": "對-甲苯基溴化鎂",
    "p-tolyltrichlorosilane": "對-甲苯基三氯矽烷",
    "p-vinylbenzoic acid": "對乙烯基苯甲酸",
    "p-xylene": "對二甲苯",
    "p-xylylenebis(tetrahydrothiophenium chloride)": "對-二甲苯雙",
    "palladium": "鈀粉",
    "palladium (metal)": "鈀",
    "palladium on carbon (pd/c)": "鈀碳",
    "palladium(ii) acetate": "醋酸鈀",
    "palladium(ii) chloride": "氯化鈀",
    "palmitic acid": "棕櫚酸",
    "palmitoyl chloride": "棕櫚醯氯",
    "paraformaldehyde": "多聚甲醛",
    "pedot:pss": "聚",
    "penicillamine": "青黴胺",
    "pentacene": "並五苯",
    "pentadecanolide": "十五內酯",
    "pentafluoroiodobenzene": "五氟碘苯",
    "pentafluorophenylboronic acid": "五氟苯硼酸",
    "pentafluorophenylmagnesium bromide": "五氟苯基溴化鎂",
    "pentafluoropyridine": "五氟吡啶",
    "pentane": "戊烷",
    "pentyltrichlorosilane": "戊基三氯矽烷",
    "peppermint oil": "薄荷油",
    "perfluoro-n-hexyl iodide": "全氟己基碘",
    "perfluorobutyl iodide": "全氟丁基碘",
    "perfluorododecyl iodide": "全氟十二烷基碘",
    "perfluorohexadecanoic acid": "全氟十六酸",
    "perfluorooctanoic acid": "全氟辛酸",
    "perfluoropropyl iodide": "全氟丙基碘",
    "perfluorosulfonic acid-ptfe copolymer": "全氟磺酸-PTFE共聚物",
    "periodic acid": "過碘酸",
    "perylene-3,4,9,10-tetracarboxylic dianhydride": "苝-3,4,9,10-四甲酸二酐",
    "phenanthrene": "菲",
    "phenanthrene-9,10-quinone": "9,10-菲醌",
    "phenazine": "吩嗪",
    "phenol": "苯酚",
    "phenolphthalein": "酚酞",
    "phenothiazine": "吩噻嗪",
    "phenoxazine": "吩噁嗪",
    "phenyl chloroformate": "氯甲酸苯酯",
    "phenyl propargyl ether": "苯基炔丙基醚",
    "phenylacetyl chloride": "苯乙醯氯",
    "phenylacetylene": "苯乙炔",
    "phenylboronic acid": "苯硼酸",
    "phenylboronic acid neopentylglycol ester": "苯硼酸新戊二醇酯",
    "phenylboronic acid pinacol ester": "苯硼酸頻那醇酯",
    "phenylhydrazine": "苯肼",
    "phenyllithium": "苯基鋰",
    "phenylmagnesium bromide": "苯基溴化鎂",
    "phenylmagnesium chloride": "苯基氯化鎂",
    "phenylpropiolaldehyde": "苯丙炔醛",
    "phenylpropiolic acid": "苯丙炔酸",
    "phenyltrichlorosilane": "苯基三氯矽烷",
    "phenyltrimethylammonium tribromide": "苯基三甲基三溴化銨",
    "phosphinic acid, sodium salt, monohydrate": "次磷酸鈉一水合物",
    "phosphomolybdic acid hydrate": "磷鉬酸水合物",
    "phosphoric acid": "磷酸",
    "phosphorus oxychloride": "三氯氧磷",
    "phosphorus pentachloride": "五氯化磷",
    "phosphorus pentasulfide": "五硫化二磷",
    "phosphorus pentoxide": "五氧化二磷",
    "phosphorus tribromide": "三溴化磷",
    "phosphorus trichloride": "三氯化磷",
    "phthalic anhydride": "鄰苯二甲酸酐",
    "phthalimide potassium salt": "鄰苯二甲醯亞胺鉀",
    "phthaloyl dichloride": "鄰苯二甲醯氯",
    "pimelic acid": "庚二酸",
    "pinacol (2,3-dimethyl-2,3-butanediol)": "頻那醇",
    "piperidine": "哌啶",
    "pivalic acid (trimethylacetic acid)": "三甲基乙酸",
    "pivaloylacetonitrile": "特戊醯乙腈",
    "poloxamer (polyethylene-polypropylene glycol)": "泊洛沙姆",
    "poly(4-vinylphenol)": "聚",
    "poly(9-vinylcarbazole)": "聚",
    "poly(ethylene glycol) (peg)": "聚乙二醇",
    "poly(ethylene glycol) dimethyl ether": "聚乙二醇二甲醚",
    "poly(ethylene)": "聚乙烯",
    "poly(methacrylic acid, sodium salt)": "聚甲基丙烯酸鈉",
    "poly(methyl methacrylate)": "聚甲基丙烯酸甲酯",
    "poly(methyl methacrylate) (pmma)": "聚甲基丙烯酸甲酯",
    "poly(methylhydrosiloxane)": "聚甲基氫矽氧烷",
    "poly(propylene glycol) (ppg)": "聚丙二醇",
    "poly(sodium vinylsulfonate)": "聚乙烯磺酸鈉",
    "poly(vinyl alcohol)": "聚乙烯醇",
    "poly(vinylidene fluoride) (pvdf)": "聚偏二氟乙烯",
    "polyethylenimine": "聚乙烯亞胺",
    "polyphosphoric acid": "多磷酸",
    "polyvinylpyrrolidone (pvp)": "聚維酮",
    "potassium": "鉀",
    "potassium acetate": "醋酸鉀",
    "potassium bromate": "溴酸鉀",
    "potassium bromide": "溴化鉀",
    "potassium carbonate": "碳酸鉀",
    "potassium chloride": "氯化鉀",
    "potassium dihydrogen phosphate": "磷酸二氫鉀",
    "potassium disulfate (potassium pyrosulfate)": "焦硫酸鉀",
    "potassium ethyl xanthate": "乙基黃原酸鉀",
    "potassium fluoride": "氟化鉀",
    "potassium fluoroborate": "氟硼酸鉀",
    "potassium hexacyanoferrate(ii) trihydrate": "亞鐵氰化鉀三水合物",
    "potassium hexacyanoferrate(iii)": "鐵氰化鉀",
    "potassium hydrogen sulphate": "硫酸氫鉀",
    "potassium hydroxide": "氫氧化鉀",
    "potassium iodate": "碘酸鉀",
    "potassium iodide": "碘化鉀",
    "potassium metabisulfite": "焦亞硫酸鉀",
    "potassium nitrate": "硝酸鉀",
    "potassium permanganate": "過錳酸鉀",
    "potassium peroxomonosulfate": "過一硫酸鉀",
    "potassium peroxymonosulfate (oxone)": "過一硫酸氫鉀",
    "potassium persulfate": "過硫酸鉀",
    "potassium phosphate monobasic": "磷酸二氫鉀",
    "potassium phosphate tribasic": "磷酸鉀",
    "potassium phosphate tribasic monohydrate": "磷酸鉀",
    "potassium sodium tartrate tetrahydrate": "酒石酸鉀鈉四水合物",
    "potassium sulfate": "硫酸鉀",
    "potassium tert-butoxide": "三級丁醇鉀",
    "potassium tetrachloroplatinate": "四氯鉑酸鉀",
    "potassium tetrachloroplatinate(ii)": "四氯鉑酸鉀",
    "potassium thioacetate": "硫代醋酸鉀",
    "potassium thiocyanate": "硫氰酸鉀",
    "precocene i": "早熟素 I",
    "precocene ii (6,7-dimethoxy-2,2-dimethyl-3-chromene)": "早熟素 II",
    "propargyl alcohol": "炔丙醇",
    "propiolic acid": "丙炔酸",
    "propionaldehyde": "丙醛",
    "propionic acid cyclohexyl ester": "丙酸環己酯",
    "propylene carbonate": "碳酸丙烯酯",
    "propyltrichlorosilane": "丙基三氯矽烷",
    "pybop": "(苯并三唑-1-基氧基)三吡咯烷基鏻六氟磷酸鹽",
    "pyrazinecarboxylic acid": "吡嗪甲酸",
    "pyrene": "芘",
    "pyridin-4-ylmagnesium bromide": "吡啶-4-基溴化鎂",
    "pyridine": "吡啶",
    "pyridine-3-boronic acid": "吡啶-3-硼酸",
    "pyridine-4-boronic acid": "吡啶-4-硼酸",
    "pyridine-4-boronic acid pinacol ester": "吡啶-4-硼酸頻那醇酯",
    "pyridine-d5": "吡啶-d5",
    "pyridinium bromide": "溴化吡啶",
    "pyridinium dichromate": "重鉻酸吡啶鹽",
    "pyrocatechol": "鄰苯二酚",
    "pyromellitic dianhydride (pmda)": "均苯四甲酸二酐",
    "pyrrolidine": "吡咯烷",
    "quinizarin": "奎茜",
    "quinoline": "喹啉",
    "quinone": "苯醌",
    "resorcinol": "雷索辛",
    "rubrene": "紅螢烯",
    "ruthenium chloride n-hydrate": "氯化釕水合物",
    "samarium(iii) nitrate hexahydrate": "硝酸釤",
    "sandalwood oil": "檀香油",
    "scandium(iii) trifluoromethanesulfonate": "三氟甲磺酸鈧",
    "sea sand (quartz)": "海砂",
    "selectfluor (f-teda-bf4)": "選擇性氟試劑",
    "selenium dioxide": "二氧化硒",
    "silica gel": "矽膠",
    "silica gel (orange)": "矽膠",
    "silica gel 60": "矽膠 60",
    "silicon dioxide": "二氧化矽",
    "silicon tetrachloride": "四氯化矽",
    "silver (shot/pellets)": "銀粒/銀靶材",
    "silver acetate": "醋酸銀",
    "silver bromide": "溴化銀",
    "silver chloride": "氯化銀",
    "silver iodide": "碘化銀",
    "silver nitrate": "硝酸銀",
    "silver perchlorate monohydrate": "過氯酸銀一水合物",
    "silver sulfate": "硫酸銀",
    "silver trifluoromethanesulfonate": "三氟甲磺酸銀",
    "silver(i) oxide": "氧化銀",
    "sinapic acid": "芥子酸",
    "sodium": "鈉",
    "sodium acetate": "醋酸鈉",
    "sodium acetate anhydrous": "醋酸鈉",
    "sodium amide": "胺基鈉",
    "sodium azide": "疊氮化鈉",
    "sodium benzoate": "苯甲酸鈉",
    "sodium bis(2-methoxyethoxy)aluminium hydride": "雙",
    "sodium bis(2-methoxyethoxy)aluminum hydride (red-al)": "紅鋁",
    "sodium bisulfate monohydrate": "硫酸氫鈉一水合物",
    "sodium bisulfite": "亞硫酸氫鈉",
    "sodium borohydride": "硼氫化鈉",
    "sodium carbonate": "碳酸鈉",
    "sodium chloride": "氯化鈉",
    "sodium chlorite": "亞氯酸鈉",
    "sodium citrate dihydrate": "檸檬酸鈉二水合物",
    "sodium cyanide": "氰化鈉",
    "sodium cyanoborohydride": "氰基硼氫化鈉",
    "sodium dodecyl sulfate (sds)": "十二烷基硫酸鈉",
    "sodium ethoxide": "乙醇鈉",
    "sodium fluoride": "氟化鈉",
    "sodium fluoroacetate": "氟乙酸鈉",
    "sodium hydride": "氫化鈉",
    "sodium hydrogen 4-chlorophthalate": "4-氯鄰苯二甲酸氫鈉",
    "sodium hydrogen carbonate": "碳酸氫鈉",
    "sodium hydrogen sulfate": "硫酸氫鈉",
    "sodium hydrosulfide hydrate": "硫氫化鈉水合物",
    "sodium hydroxide": "氫氧化鈉",
    "sodium hypochlorite": "次氯酸鈉",
    "sodium hypophosphite monohydrate": "次磷酸鈉一水合物",
    "sodium iodide": "碘化鈉",
    "sodium iodide (anhydrous)": "碘化鈉",
    "sodium iodide anhydrous": "碘化鈉",
    "sodium l-ascorbate": "L-抗壞血酸鈉",
    "sodium lauryl sulfate (sds)": "十二烷基硫酸鈉",
    "sodium metabisulfite": "偏亞硫酸氫鈉",
    "sodium metasilicate pentahydrate": "偏矽酸鈉五水合物",
    "sodium methoxide": "甲醇鈉",
    "sodium methylate": "甲醇鈉",
    "sodium nitrate": "硝酸鈉",
    "sodium nitrite": "亞硝酸鈉",
    "sodium perborate monohydrate": "過硼酸鈉一水合物",
    "sodium percarbonate": "過碳酸鈉",
    "sodium periodate": "過碘酸鈉",
    "sodium phosphate monobasic": "磷酸二氫鈉",
    "sodium phosphate tribasic dodecahydrate": "磷酸鈉",
    "sodium sulfate": "硫酸鈉",
    "sodium sulfide hydrate": "硫化鈉水合物",
    "sodium sulfite": "亞硫酸鈉",
    "sodium tert-butoxide": "三級丁醇鈉",
    "sodium thiomethoxide": "甲硫醇鈉",
    "sodium thiosulfate": "硫代硫酸鈉",
    "sodium tin(iv) oxide trihydrate (sodium stannate)": "錫酸鈉三水合物",
    "sodium triflinate (sodium trifluoromethanesulfinate)": "三氟甲亞磺酸鈉",
    "sodium trifluoroacetate": "三氟乙酸鈉",
    "sphos (2-dicyclohexylphosphino-2',6'-dimethoxybiphenyl)": "SPhos 配體",
    "spiro-meotad": "Spiro-MeOTAD",
    "spiro-ometad": "Spiro-OMeTAD",
    "stannic chloride (tin(iv) chloride)": "氯化錫",
    "stearic acid": "硬脂酸",
    "styrene": "苯乙烯",
    "succinic acid": "琥珀酸",
    "succinic anhydride": "丁二酸酐",
    "sulfur": "硫磺",
    "sulfur powder": "硫粉",
    "sulfuric acid": "硫酸",
    "sulfuryl chloride": "硫醯氯",
    "tbuxphos": "tBuXPhos",
    "terephthalaldehyde": "對苯二甲醛",
    "terephthalaldehydic acid (4-formylbenzoic acid)": "對苯二甲醛酸",
    "terephthalic acid": "對苯二甲酸",
    "terephthalic acid, diethyl ester": "對苯二甲酸二乙酯",
    "terephthalonitrile": "對苯二甲腈",
    "tert-butyl alcohol": "三級丁醇",
    "tert-butyl bromoacetate": "溴乙酸三級丁酯",
    "tert-butyl nitrite": "亞硝酸三級丁酯",
    "tert-butyl sulfide": "叔丁基硫醚",
    "tert-butylamine": "三級丁胺",
    "tert-butyllithium": "叔丁基鋰",
    "tetra-n-butylammonium bromide (tbab)": "四丁基溴化銨",
    "tetra-n-butylammonium hexafluorophosphate": "六氟磷酸四丁基銨",
    "tetra-n-butylammonium iodide": "四丁基碘化銨",
    "tetrabromomethane": "四溴甲烷",
    "tetrabromothiophene": "四溴噻吩",
    "tetrabutylammonium acetate": "四丁基醋酸銨",
    "tetrabutylammonium borohydride": "硼氫化四丁基銨",
    "tetrabutylammonium bromide (tbab)": "四丁基溴化銨",
    "tetrabutylammonium cyanide": "四丁基氰化銨",
    "tetrabutylammonium fluoride (tbaf)": "四丁基氟化銨",
    "tetrabutylammonium fluoride trihydrate": "四丁基氟化銨三水合物",
    "tetrabutylammonium fluoride trihydrate (tbaf)": "四丁基氟化銨三水合物",
    "tetrabutylammonium hexafluorophosphate": "六氟磷酸四丁基銨",
    "tetrabutylammonium iodide": "四丁基碘化銨",
    "tetrabutylammonium perchlorate": "過氯酸四丁基銨",
    "tetrabutylammonium phosphate": "四丁基磷酸銨",
    "tetrabutylammonium tetrafluoroborate": "四氟硼酸四丁基銨",
    "tetrabutylphosphonium bromide": "溴化四丁基磷",
    "tetrabutylphosphonium chloride": "氯化四丁基磷",
    "tetrachloroethylene": "四氯乙烯",
    "tetrachloromethane (carbon tetrachloride)": "四氯化碳",
    "tetrachlorophthalic anhydride": "四氯鄰苯二甲酸酐",
    "tetracyanoethylene": "四氰乙烯",
    "tetradecanal": "十四醛",
    "tetradecanedioic acid": "十四烷二酸",
    "tetradecylphosphonic acid": "十四烷基膦酸",
    "tetraethyl orthosilicate": "正矽酸四乙酯",
    "tetraethylene glycol": "四乙二醇",
    "tetraethylene glycol monomethyl ether": "四乙二醇單甲醚",
    "tetrafluoroboric acid": "四氟硼酸",
    "tetrafluorophthalic acid": "四氟鄰苯二甲酸",
    "tetrahydrofuran": "四氫呋喃",
    "tetrahydrofuran (thf)": "四氫呋喃",
    "tetrahydrofuran-d8": "四氫呋喃-d8",
    "tetrakis(hydroxymethyl)phosphonium chloride (thpc)": "四羥甲基氯化磷",
    "tetrakis(triphenylphosphine)palladium(0)": "四",
    "tetrakis(triphenylphosphine)platinum(0)": "四",
    "tetraoctylammonium bromide": "四辛基溴化銨",
    "tetraphenylphosphonium bromide": "四苯基溴化鏻",
    "thallium(i) nitrate": "硝酸鉈",
    "thallium(iii) nitrate": "硝酸鉈",
    "thianaphthene-2-boronic acid (benzo[b]thiophene-2-boronic acid)": "苯并[b]噻吩-2-硼酸",
    "thieno[3,2-b]thiophene": "噻吩并[3,2-b]噻吩",
    "thieno[3,2-b]thiophene-2,5-dicarbaldehyde": "噻吩并[3,2-b]噻吩-2,5-二甲醛",
    "thieno[3,2-b]thiophene-2-carboxaldehyde": "噻吩并[3,2-b]噻吩-2-甲醛",
    "thioacetamide": "硫代乙醯胺",
    "thioacetic acid": "硫代乙酸",
    "thioanisole": "苯甲硫醚",
    "thiobenzoic acid": "硫代苯甲酸",
    "thioglycol": "2-巰基乙醇",
    "thionyl chloride": "亞硫醯氯",
    "thiophene": "噻吩",
    "thiophene-2-carboxaldehyde": "2-噻吩甲醛",
    "thiophene-3-boronic acid": "噻吩-3-硼酸",
    "thiophene-3-carboxaldehyde": "3-噻吩甲醛",
    "thiophenol": "苯硫酚",
    "thiophosgene": "硫光氣",
    "thiourea": "硫脲",
    "thioxanthone": "硫雜蒽酮",
    "tigloyl chloride": "惕各醯氯",
    "tin": "錫",
    "tin (ii) iodide": "碘化亞錫",
    "tin (iv) chloride": "氯化錫",
    "tin(ii) chloride": "氯化錫",
    "tin(ii) chloride dihydrate": "氯化亞錫二水合物",
    "titanium diisopropoxide bis(acetylacetonate)": "二異丙氧基雙",
    "titanium tetrachloride": "四氯化鈦",
    "titanium(ii) oxide": "一氧化鈦",
    "titanium(iv) isopropoxide": "異丙醇鈦",
    "toluene": "甲苯",
    "trans-1,2-bis(tri-n-butylstannyl)ethylene": "反式-1,2-雙",
    "trans-2-hexen-1-ol": "反式-2-己烯-1-醇",
    "trans-2-hexenoic acid": "反式-2-己烯酸",
    "trans-chrysanthemyl alcohol": "反式菊醇",
    "trans-cyclobutane-1,2-dicarbonyl chloride": "反式-環丁烷-1,2-二甲醯氯",
    "tri(o-tolyl)phosphine": "三",
    "tri-tert-butylphosphonium tetrafluoroborate": "三-三級丁基磷四氟硼酸鹽",
    "triacontanoic acid": "三十酸",
    "tributyl borate": "硼酸三丁酯",
    "tributylamine": "三丁胺",
    "tributylphosphine": "三丁基膦",
    "tributyltin chloride": "三丁基氯化錫",
    "trichloro(1h,1h,2h,2h-perfluorooctyl)silane": "(1H,1H,2H,2H-全氟辛基)三氯矽烷",
    "trichloroacetic acid": "三氯乙酸",
    "trichloroacetonitrile": "三氯乙腈",
    "trichloromethane": "三氯甲烷",
    "trichloromethane (chloroform)": "三氯甲烷",
    "trichlorosilane": "三氯矽烷",
    "tricosafluorododecanoic acid": "全氟十二酸",
    "tricyclohexylphosphine": "三環己基膦",
    "tridecanoic acid": "十三酸",
    "triethanolamine": "三乙醇胺",
    "triethyl 1,3,5-benzenetricarboxylate": "1,3,5-苯三甲酸三乙酯",
    "triethyl 4-phosphonocrotonate": "4-膦酸巴豆酸三乙酯",
    "triethyl orthoacetate": "原乙酸三乙酯",
    "triethyl phosphate": "磷酸三乙酯",
    "triethyl phosphite": "亞磷酸三乙酯",
    "triethyl phosphonoacetate": "膦酸乙酸三乙酯",
    "triethylamine": "三乙胺",
    "triethylene glycol monomethyl ether": "三乙二醇單甲醚",
    "triethylenediamine": "三乙烯二胺",
    "triethylphosphine": "三乙基膦",
    "triethylsilane": "三乙基矽烷",
    "trifluoroacetic acid": "三氟乙酸",
    "trifluoroacetic acid (tfa)": "三氟乙酸",
    "trifluoroacetic acid anhydride": "三氟乙酸酐",
    "trifluoroacetic anhydride": "三氟乙酸酐",
    "trifluoromethanesulfonic acid": "三氟甲磺酸",
    "trifluoromethanesulfonic anhydride": "三氟甲磺酸酐",
    "trifluoromethanesulphonic acid": "三氟甲磺酸",
    "trifluoromethanesulphonic anhydride": "三氟甲磺酸酐",
    "trifluoromethyltrimethylsilane": "三氟甲基三甲基矽烷",
    "trifluoromethyltrimethylsilane (ruppert-prakash reagent)": "三氟甲基三甲基矽烷",
    "triisopropyl borate": "硼酸三異丙酯",
    "triisopropyl phosphite": "亞磷酸三異丙酯",
    "triisopropylsilane": "三異丙基矽烷",
    "triisopropylsilane (tips)": "三異丙基矽烷",
    "trimesic acid": "均苯三甲酸",
    "trimesic acid trichloride": "均苯三甲醯氯",
    "trimesic acid trichloride (1,3,5-benzenetricarbonyl chloride)": "1,3,5-苯三甲醯氯",
    "trimethoxy(7-octen-1-yl)silane": "7-辛烯基三甲氧基矽烷",
    "trimethoxy(octyl)silane": "三甲氧基辛基矽烷",
    "trimethyl borate": "硼酸三甲酯",
    "trimethylacetonitrile (pivalonitrile)": "特戊腈",
    "trimethylamine": "三甲胺",
    "trimethylborate": "硼酸三甲酯",
    "trimethylbromosilane": "三甲基溴矽烷",
    "trimethylchlorosilane": "三甲基氯矽烷",
    "trimethylhexadecylammonium chloride": "十六烷基三甲基氯化銨",
    "trimethylphosphite": "亞磷酸三甲酯",
    "trimethylsilylacetylene": "三甲基矽乙炔",
    "trimethylsulfonium iodide": "三甲基碘化硫",
    "trimethyltin chloride": "三甲基氯化錫",
    "triphenylamine": "三苯胺",
    "triphenylene": "三亞苯",
    "triphenylmethanol": "三苯甲醇",
    "triphenylphosphine": "三苯基膦",
    "triphenylsilyl chloride": "三苯基氯矽烷",
    "triphosgene": "三光氣",
    "tripropylamine": "三丙胺",
    "triptycene": "三亞甲苯",
    "tris(4-bromophenyl)amine": "三",
    "tris(4-nitrophenyl)amine": "三",
    "tris(dibenzylideneacetone)dipalladium(0)": "三",
    "tris(dibenzylideneacetone)dipalladium(0) (pd2(dba)3)": "三",
    "tris(dibenzylideneacetone)dipalladium(0)-chloroform adduct": "三",
    "trityl chloride (triphenylmethyl chloride)": "三苯甲基氯",
    "trizma® hydrochloride (tris hcl)": "Tris-HCl",
    "tungstic acid": "鎢酸",
    "undecanedioic acid": "十一烷二酸",
    "undecylenic acid": "十一烯酸",
    "urea": "尿素",
    "valeryl chloride": "戊醯氯",
    "vanadium pentoxide": "五氧化二釩",
    "veratric acid": "藜蘆酸",
    "veratric acid (3,4-dimethoxybenzoic acid)": "藜蘆酸",
    "vinylene carbonate": "碳酸亞乙烯酯",
    "vinylmethylsiloxane-dimethylsiloxane copolymer": "乙烯基甲基矽氧烷-二甲基矽氧烷共聚物",
    "vinylphosphonic acid": "乙烯基膦酸",
    "wang resin": "Wang 樹脂",
    "xanthone": "氧雜蒽酮",
    "xphos": "XPhos",
    "xylenes": "二甲苯",
    "zinc acetate": "醋酸鋅",
    "zinc acetate dihydrate": "醋酸鋅二水合物",
    "zinc bromide": "溴化鋅",
    "zinc chloride": "氯化鋅",
    "zinc iodide": "碘化鋅",
    "zinc nitrate hexahydrate": "硝酸鋅六水合物",
    "zinc powder": "鋅粉",
}
